# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nxtWin7_h900.ui'
#
# Created: Mon May 26 12:24:44 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1280, 880)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1280, 900))
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget_Req = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_Req.setGeometry(QtCore.QRect(390, 0, 351, 831))
        self.tabWidget_Req.setObjectName(_fromUtf8("tabWidget_Req"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 65, 341, 396))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(6, 0, 0, 8)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit1_nxtQ3 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ3.setObjectName(_fromUtf8("lineEdit1_nxtQ3"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ3, 2, 0, 1, 1)
        self.lineEdit1_nxtQ6_Val6 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ6_Val6.setObjectName(_fromUtf8("lineEdit1_nxtQ6_Val6"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ6_Val6, 5, 1, 1, 1)
        self.lineEdit1_nxtQ2 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ2.setObjectName(_fromUtf8("lineEdit1_nxtQ2"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ2, 1, 0, 1, 1)
        self.lineEdit1_nxtQ8_Val8 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ8_Val8.setObjectName(_fromUtf8("lineEdit1_nxtQ8_Val8"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ8_Val8, 7, 1, 1, 1)
        self.lineEdit1_nxtQ5 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ5.setObjectName(_fromUtf8("lineEdit1_nxtQ5"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ5, 4, 0, 1, 1)
        self.lineEdit1_nxtQ7_Val7 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ7_Val7.setObjectName(_fromUtf8("lineEdit1_nxtQ7_Val7"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ7_Val7, 6, 1, 1, 1)
        self.lineEdit1_nxtQ6 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ6.setObjectName(_fromUtf8("lineEdit1_nxtQ6"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ6, 5, 0, 1, 1)
        self.lineEdit1_nxtQ2_Val2 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ2_Val2.setObjectName(_fromUtf8("lineEdit1_nxtQ2_Val2"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ2_Val2, 1, 1, 1, 1)
        self.lineEdit1_nxtQ7 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ7.setObjectName(_fromUtf8("lineEdit1_nxtQ7"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ7, 6, 0, 1, 1)
        self.lineEdit1_nxtQ9_Val9 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ9_Val9.setObjectName(_fromUtf8("lineEdit1_nxtQ9_Val9"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ9_Val9, 8, 1, 1, 1)
        self.lineEdit1_nxtQ3_Val3 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ3_Val3.setObjectName(_fromUtf8("lineEdit1_nxtQ3_Val3"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ3_Val3, 2, 1, 1, 1)
        self.lineEdit1_nxtQ5_Val5 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ5_Val5.setObjectName(_fromUtf8("lineEdit1_nxtQ5_Val5"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ5_Val5, 4, 1, 1, 1)
        self.lineEdit1_nxtQ8 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ8.setObjectName(_fromUtf8("lineEdit1_nxtQ8"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ8, 7, 0, 1, 1)
        self.lineEdit1_nxtQ1 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ1.setObjectName(_fromUtf8("lineEdit1_nxtQ1"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ1, 0, 0, 1, 1)
        self.lineEdit1_nxtQ1_Val1 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ1_Val1.setObjectName(_fromUtf8("lineEdit1_nxtQ1_Val1"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ1_Val1, 0, 1, 1, 1)
        self.lineEdit1_nxtQ9 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ9.setObjectName(_fromUtf8("lineEdit1_nxtQ9"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ9, 8, 0, 1, 1)
        self.lineEdit1_nxtQ4 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ4.setObjectName(_fromUtf8("lineEdit1_nxtQ4"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ4, 3, 0, 1, 1)
        self.lineEdit1_nxtQ4_Val4 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ4_Val4.setObjectName(_fromUtf8("lineEdit1_nxtQ4_Val4"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ4_Val4, 3, 1, 1, 1)
        self.lineEdit1_nxtQ10_Val10 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ10_Val10.setObjectName(_fromUtf8("lineEdit1_nxtQ10_Val10"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ10_Val10, 9, 1, 1, 1)
        self.lineEdit1_nxtQ10 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ10.setObjectName(_fromUtf8("lineEdit1_nxtQ10"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ10, 9, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.label_serverAddress = QtGui.QLabel(self.tab)
        self.label_serverAddress.setGeometry(QtCore.QRect(0, 0, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_serverAddress.setFont(font)
        self.label_serverAddress.setAlignment(QtCore.Qt.AlignCenter)
        self.label_serverAddress.setObjectName(_fromUtf8("label_serverAddress"))
        self.label_account = QtGui.QLabel(self.tab)
        self.label_account.setGeometry(QtCore.QRect(0, 30, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_account.setFont(font)
        self.label_account.setAlignment(QtCore.Qt.AlignCenter)
        self.label_account.setObjectName(_fromUtf8("label_account"))
        self.lineEdit_account7 = QtGui.QLineEdit(self.tab)
        self.lineEdit_account7.setGeometry(QtCore.QRect(70, 30, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_account7.setFont(font)
        self.lineEdit_account7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_account7.setObjectName(_fromUtf8("lineEdit_account7"))
        self.lineEdit_nxtServer = QtGui.QLineEdit(self.tab)
        self.lineEdit_nxtServer.setGeometry(QtCore.QRect(70, 0, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_nxtServer.setFont(font)
        self.lineEdit_nxtServer.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nxtServer.setObjectName(_fromUtf8("lineEdit_nxtServer"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 465, 341, 316))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pb_cancelAskOrder = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_cancelAskOrder.setFont(font)
        self.pb_cancelAskOrder.setObjectName(_fromUtf8("pb_cancelAskOrder"))
        self.gridLayout_3.addWidget(self.pb_cancelAskOrder, 8, 0, 1, 1)
        self.pb_getAssetIds = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAssetIds.setFont(font)
        self.pb_getAssetIds.setObjectName(_fromUtf8("pb_getAssetIds"))
        self.gridLayout_3.addWidget(self.pb_getAssetIds, 2, 1, 1, 1)
        self.pb_issueAsset = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_issueAsset.setFont(font)
        self.pb_issueAsset.setObjectName(_fromUtf8("pb_issueAsset"))
        self.gridLayout_3.addWidget(self.pb_issueAsset, 0, 0, 1, 1)
        self.pb_getAsset = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAsset.setFont(font)
        self.pb_getAsset.setObjectName(_fromUtf8("pb_getAsset"))
        self.gridLayout_3.addWidget(self.pb_getAsset, 2, 0, 1, 1)
        self.pb_cancelBidOrder = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_cancelBidOrder.setFont(font)
        self.pb_cancelBidOrder.setObjectName(_fromUtf8("pb_cancelBidOrder"))
        self.gridLayout_3.addWidget(self.pb_cancelBidOrder, 8, 1, 1, 1)
        self.pb_placeBidOrder = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_placeBidOrder.setFont(font)
        self.pb_placeBidOrder.setObjectName(_fromUtf8("pb_placeBidOrder"))
        self.gridLayout_3.addWidget(self.pb_placeBidOrder, 7, 1, 1, 1)
        self.pb_getAskOrder = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAskOrder.setFont(font)
        self.pb_getAskOrder.setObjectName(_fromUtf8("pb_getAskOrder"))
        self.gridLayout_3.addWidget(self.pb_getAskOrder, 10, 0, 1, 1)
        self.pb_getAskOrderIds = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAskOrderIds.setFont(font)
        self.pb_getAskOrderIds.setObjectName(_fromUtf8("pb_getAskOrderIds"))
        self.gridLayout_3.addWidget(self.pb_getAskOrderIds, 9, 0, 1, 1)
        self.pb_getBidOrder = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getBidOrder.setFont(font)
        self.pb_getBidOrder.setObjectName(_fromUtf8("pb_getBidOrder"))
        self.gridLayout_3.addWidget(self.pb_getBidOrder, 10, 1, 1, 1)
        self.pb_getBidOrderIds = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getBidOrderIds.setFont(font)
        self.pb_getBidOrderIds.setObjectName(_fromUtf8("pb_getBidOrderIds"))
        self.gridLayout_3.addWidget(self.pb_getBidOrderIds, 9, 1, 1, 1)
        self.pb_placeAskOrder = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_placeAskOrder.setFont(font)
        self.pb_placeAskOrder.setObjectName(_fromUtf8("pb_placeAskOrder"))
        self.gridLayout_3.addWidget(self.pb_placeAskOrder, 7, 0, 1, 1)
        self.pb_getAccountCurrentBidOrderIds = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAccountCurrentBidOrderIds.setFont(font)
        self.pb_getAccountCurrentBidOrderIds.setObjectName(_fromUtf8("pb_getAccountCurrentBidOrderIds"))
        self.gridLayout_3.addWidget(self.pb_getAccountCurrentBidOrderIds, 6, 1, 1, 1)
        self.pb_getAccountCurrentAskOrderIds = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAccountCurrentAskOrderIds.setFont(font)
        self.pb_getAccountCurrentAskOrderIds.setObjectName(_fromUtf8("pb_getAccountCurrentAskOrderIds"))
        self.gridLayout_3.addWidget(self.pb_getAccountCurrentAskOrderIds, 6, 0, 1, 1)
        self.pb_transferAsset = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_transferAsset.setFont(font)
        self.pb_transferAsset.setObjectName(_fromUtf8("pb_transferAsset"))
        self.gridLayout_3.addWidget(self.pb_transferAsset, 0, 1, 1, 1)
        self.pb_getAssetsByName = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAssetsByName.setFont(font)
        self.pb_getAssetsByName.setObjectName(_fromUtf8("pb_getAssetsByName"))
        self.gridLayout_3.addWidget(self.pb_getAssetsByName, 3, 1, 1, 1)
        self.pb_getAllTrades = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_getAllTrades.setFont(font)
        self.pb_getAllTrades.setObjectName(_fromUtf8("pb_getAllTrades"))
        self.gridLayout_3.addWidget(self.pb_getAllTrades, 4, 1, 1, 1)
        self.pb_getTrades = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_getTrades.setFont(font)
        self.pb_getTrades.setObjectName(_fromUtf8("pb_getTrades"))
        self.gridLayout_3.addWidget(self.pb_getTrades, 3, 0, 1, 1)
        self.pb_getAllOpenOrders = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAllOpenOrders.setFont(font)
        self.pb_getAllOpenOrders.setObjectName(_fromUtf8("pb_getAllOpenOrders"))
        self.gridLayout_3.addWidget(self.pb_getAllOpenOrders, 4, 0, 1, 1)
        self.pb_getAllAssets = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAllAssets.setFont(font)
        self.pb_getAllAssets.setObjectName(_fromUtf8("pb_getAllAssets"))
        self.gridLayout_3.addWidget(self.pb_getAllAssets, 1, 0, 1, 1)
        self.pb_getAssets = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAssets.setFont(font)
        self.pb_getAssets.setObjectName(_fromUtf8("pb_getAssets"))
        self.gridLayout_3.addWidget(self.pb_getAssets, 1, 1, 1, 1)
        self.tabWidget_Req.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 80, 331, 581))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lineEdit_sessDat1_10 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_10.setFont(font)
        self.lineEdit_sessDat1_10.setMaxLength(2000)
        self.lineEdit_sessDat1_10.setObjectName(_fromUtf8("lineEdit_sessDat1_10"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_10, 13, 1, 1, 1)
        self.lineEdit_sessDat1_14 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_14.setFont(font)
        self.lineEdit_sessDat1_14.setMaxLength(2000)
        self.lineEdit_sessDat1_14.setObjectName(_fromUtf8("lineEdit_sessDat1_14"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_14, 17, 1, 1, 1)
        self.lineEdit_sessDat1 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1.setFont(font)
        self.lineEdit_sessDat1.setMaxLength(2000)
        self.lineEdit_sessDat1.setObjectName(_fromUtf8("lineEdit_sessDat1"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1, 4, 1, 1, 1)
        self.lineEdit_sessDat1_6 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_6.setFont(font)
        self.lineEdit_sessDat1_6.setMaxLength(2000)
        self.lineEdit_sessDat1_6.setObjectName(_fromUtf8("lineEdit_sessDat1_6"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_6, 9, 1, 1, 1)
        self.label_NXTServer = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_NXTServer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NXTServer.setObjectName(_fromUtf8("label_NXTServer"))
        self.gridLayout_6.addWidget(self.label_NXTServer, 0, 0, 1, 1)
        self.lineEdit_passPhr7 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_passPhr7.setFont(font)
        self.lineEdit_passPhr7.setMaxLength(200)
        self.lineEdit_passPhr7.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_passPhr7.setObjectName(_fromUtf8("lineEdit_passPhr7"))
        self.gridLayout_6.addWidget(self.lineEdit_passPhr7, 2, 1, 1, 1)
        self.lineEdit_account1 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_account1.setFont(font)
        self.lineEdit_account1.setMaxLength(200)
        self.lineEdit_account1.setObjectName(_fromUtf8("lineEdit_account1"))
        self.gridLayout_6.addWidget(self.lineEdit_account1, 1, 1, 1, 1)
        self.label_NXTServer_2 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_NXTServer_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NXTServer_2.setObjectName(_fromUtf8("label_NXTServer_2"))
        self.gridLayout_6.addWidget(self.label_NXTServer_2, 1, 0, 1, 1)
        self.label_passPhrase = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_passPhrase.setAlignment(QtCore.Qt.AlignCenter)
        self.label_passPhrase.setObjectName(_fromUtf8("label_passPhrase"))
        self.gridLayout_6.addWidget(self.label_passPhrase, 2, 0, 1, 1)
        self.label_pubKey = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_pubKey.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pubKey.setObjectName(_fromUtf8("label_pubKey"))
        self.gridLayout_6.addWidget(self.label_pubKey, 3, 0, 1, 1)
        self.lineEdit_publicKey1 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_publicKey1.setFont(font)
        self.lineEdit_publicKey1.setMaxLength(2000)
        self.lineEdit_publicKey1.setObjectName(_fromUtf8("lineEdit_publicKey1"))
        self.gridLayout_6.addWidget(self.lineEdit_publicKey1, 3, 1, 1, 1)
        self.lineEdit_nxtServer1 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_nxtServer1.setFont(font)
        self.lineEdit_nxtServer1.setMaxLength(200)
        self.lineEdit_nxtServer1.setObjectName(_fromUtf8("lineEdit_nxtServer1"))
        self.gridLayout_6.addWidget(self.lineEdit_nxtServer1, 0, 1, 1, 1)
        self.lineEdit_sessDat1_4 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_4.setFont(font)
        self.lineEdit_sessDat1_4.setMaxLength(2000)
        self.lineEdit_sessDat1_4.setObjectName(_fromUtf8("lineEdit_sessDat1_4"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_4, 7, 1, 1, 1)
        self.lineEdit_sessDat1_8 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_8.setFont(font)
        self.lineEdit_sessDat1_8.setMaxLength(2000)
        self.lineEdit_sessDat1_8.setObjectName(_fromUtf8("lineEdit_sessDat1_8"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_8, 11, 1, 1, 1)
        self.lineEdit_sessDat1_12 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_12.setFont(font)
        self.lineEdit_sessDat1_12.setMaxLength(2000)
        self.lineEdit_sessDat1_12.setObjectName(_fromUtf8("lineEdit_sessDat1_12"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_12, 15, 1, 1, 1)
        self.lineEdit_sessDat1_2 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_2.setFont(font)
        self.lineEdit_sessDat1_2.setMaxLength(2000)
        self.lineEdit_sessDat1_2.setObjectName(_fromUtf8("lineEdit_sessDat1_2"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_2, 5, 1, 1, 1)
        self.lineEdit_sessDat1_13 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_13.setFont(font)
        self.lineEdit_sessDat1_13.setMaxLength(2000)
        self.lineEdit_sessDat1_13.setObjectName(_fromUtf8("lineEdit_sessDat1_13"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_13, 16, 1, 1, 1)
        self.lineEdit_sessDat1_7 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_7.setFont(font)
        self.lineEdit_sessDat1_7.setMaxLength(2000)
        self.lineEdit_sessDat1_7.setObjectName(_fromUtf8("lineEdit_sessDat1_7"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_7, 10, 1, 1, 1)
        self.lineEdit_sessDat1_9 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_9.setFont(font)
        self.lineEdit_sessDat1_9.setMaxLength(2000)
        self.lineEdit_sessDat1_9.setObjectName(_fromUtf8("lineEdit_sessDat1_9"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_9, 12, 1, 1, 1)
        self.lineEdit_sessDat1_11 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_11.setFont(font)
        self.lineEdit_sessDat1_11.setMaxLength(2000)
        self.lineEdit_sessDat1_11.setObjectName(_fromUtf8("lineEdit_sessDat1_11"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_11, 14, 1, 1, 1)
        self.lineEdit_sessDat1_3 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_3.setFont(font)
        self.lineEdit_sessDat1_3.setMaxLength(2000)
        self.lineEdit_sessDat1_3.setObjectName(_fromUtf8("lineEdit_sessDat1_3"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_3, 6, 1, 1, 1)
        self.lineEdit_sessDat1_5 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_5.setFont(font)
        self.lineEdit_sessDat1_5.setMaxLength(2000)
        self.lineEdit_sessDat1_5.setObjectName(_fromUtf8("lineEdit_sessDat1_5"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_5, 8, 1, 1, 1)
        self.lineEdit_sessDat1_15 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_15.setFont(font)
        self.lineEdit_sessDat1_15.setMaxLength(2000)
        self.lineEdit_sessDat1_15.setObjectName(_fromUtf8("lineEdit_sessDat1_15"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_15, 18, 1, 1, 1)
        self.pb_pullData1 = QtGui.QPushButton(self.tab_2)
        self.pb_pullData1.setGeometry(QtCore.QRect(150, 40, 181, 31))
        self.pb_pullData1.setObjectName(_fromUtf8("pb_pullData1"))
        self.tabWidget_Req.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(50, 120, 231, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget_Req.addTab(self.tab_3, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(750, 70, 521, 751))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.textEdit_NRSRaw1 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_NRSRaw1.setGeometry(QtCore.QRect(5, 20, 516, 731))
        self.textEdit_NRSRaw1.setReadOnly(True)
        self.textEdit_NRSRaw1.setObjectName(_fromUtf8("textEdit_NRSRaw1"))
        self.tabWidget_querySel = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_querySel.setGeometry(QtCore.QRect(0, 0, 381, 821))
        self.tabWidget_querySel.setObjectName(_fromUtf8("tabWidget_querySel"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 361, 781))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pb_getBlock = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getBlock.setFont(font)
        self.pb_getBlock.setObjectName(_fromUtf8("pb_getBlock"))
        self.gridLayout.addWidget(self.pb_getBlock, 19, 1, 1, 1)
        self.pb_sendMoney = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_sendMoney.setFont(font)
        self.pb_sendMoney.setObjectName(_fromUtf8("pb_sendMoney"))
        self.gridLayout.addWidget(self.pb_sendMoney, 18, 2, 1, 1)
        self.pb_stopForging = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_stopForging.setFont(font)
        self.pb_stopForging.setObjectName(_fromUtf8("pb_stopForging"))
        self.gridLayout.addWidget(self.pb_stopForging, 22, 2, 1, 1)
        self.pb_getAliasIds = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAliasIds.setFont(font)
        self.pb_getAliasIds.setObjectName(_fromUtf8("pb_getAliasIds"))
        self.gridLayout.addWidget(self.pb_getAliasIds, 16, 1, 1, 1)
        self.pb_getAccountTransactionIds = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAccountTransactionIds.setFont(font)
        self.pb_getAccountTransactionIds.setObjectName(_fromUtf8("pb_getAccountTransactionIds"))
        self.gridLayout.addWidget(self.pb_getAccountTransactionIds, 12, 1, 1, 1)
        self.pb_setAccountInfo = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_setAccountInfo.setFont(font)
        self.pb_setAccountInfo.setObjectName(_fromUtf8("pb_setAccountInfo"))
        self.gridLayout.addWidget(self.pb_setAccountInfo, 19, 2, 1, 1)
        self.pb_getAccount = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_getAccount.setFont(font)
        self.pb_getAccount.setObjectName(_fromUtf8("pb_getAccount"))
        self.gridLayout.addWidget(self.pb_getAccount, 8, 1, 1, 1)
        self.pb_getAccountId = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_getAccountId.setFont(font)
        self.pb_getAccountId.setObjectName(_fromUtf8("pb_getAccountId"))
        self.gridLayout.addWidget(self.pb_getAccountId, 9, 1, 1, 1)
        self.pb_generateToken = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_generateToken.setFont(font)
        self.pb_generateToken.setObjectName(_fromUtf8("pb_generateToken"))
        self.gridLayout.addWidget(self.pb_generateToken, 7, 1, 1, 1)
        self.pb_createPoll = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_createPoll.setFont(font)
        self.pb_createPoll.setObjectName(_fromUtf8("pb_createPoll"))
        self.gridLayout.addWidget(self.pb_createPoll, 3, 1, 1, 1)
        self.pb_getAccountPublicKey = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAccountPublicKey.setFont(font)
        self.pb_getAccountPublicKey.setObjectName(_fromUtf8("pb_getAccountPublicKey"))
        self.gridLayout.addWidget(self.pb_getAccountPublicKey, 11, 1, 1, 1)
        self.pb_getAccountBlockIds = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_getAccountBlockIds.setFont(font)
        self.pb_getAccountBlockIds.setObjectName(_fromUtf8("pb_getAccountBlockIds"))
        self.gridLayout.addWidget(self.pb_getAccountBlockIds, 10, 1, 1, 1)
        self.pb_getAliasId = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAliasId.setFont(font)
        self.pb_getAliasId.setObjectName(_fromUtf8("pb_getAliasId"))
        self.gridLayout.addWidget(self.pb_getAliasId, 13, 1, 1, 1)
        self.pb_assignAlias = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_assignAlias.setFont(font)
        self.pb_assignAlias.setObjectName(_fromUtf8("pb_assignAlias"))
        self.gridLayout.addWidget(self.pb_assignAlias, 0, 1, 1, 1)
        self.pb_getBalance = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getBalance.setFont(font)
        self.pb_getBalance.setObjectName(_fromUtf8("pb_getBalance"))
        self.gridLayout.addWidget(self.pb_getBalance, 18, 1, 1, 1)
        self.pb_castVote = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_castVote.setFont(font)
        self.pb_castVote.setObjectName(_fromUtf8("pb_castVote"))
        self.gridLayout.addWidget(self.pb_castVote, 2, 1, 1, 1)
        self.pb_broadcastTransaction = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_broadcastTransaction.setFont(font)
        self.pb_broadcastTransaction.setObjectName(_fromUtf8("pb_broadcastTransaction"))
        self.gridLayout.addWidget(self.pb_broadcastTransaction, 1, 1, 1, 1)
        self.pb_decodeHallmark = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_decodeHallmark.setFont(font)
        self.pb_decodeHallmark.setObjectName(_fromUtf8("pb_decodeHallmark"))
        self.gridLayout.addWidget(self.pb_decodeHallmark, 4, 1, 1, 1)
        self.pb_decodeToken = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_decodeToken.setFont(font)
        self.pb_decodeToken.setObjectName(_fromUtf8("pb_decodeToken"))
        self.gridLayout.addWidget(self.pb_decodeToken, 5, 1, 1, 1)
        self.pb_getConstants = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getConstants.setFont(font)
        self.pb_getConstants.setObjectName(_fromUtf8("pb_getConstants"))
        self.gridLayout.addWidget(self.pb_getConstants, 21, 1, 1, 1)
        self.pb_sendMessage = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_sendMessage.setFont(font)
        self.pb_sendMessage.setObjectName(_fromUtf8("pb_sendMessage"))
        self.gridLayout.addWidget(self.pb_sendMessage, 17, 2, 1, 1)
        self.pb_getAliasURI = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAliasURI.setFont(font)
        self.pb_getAliasURI.setObjectName(_fromUtf8("pb_getAliasURI"))
        self.gridLayout.addWidget(self.pb_getAliasURI, 17, 1, 1, 1)
        self.pb_startForging = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_startForging.setFont(font)
        self.pb_startForging.setObjectName(_fromUtf8("pb_startForging"))
        self.gridLayout.addWidget(self.pb_startForging, 21, 2, 1, 1)
        self.pb_getAlias = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAlias.setFont(font)
        self.pb_getAlias.setObjectName(_fromUtf8("pb_getAlias"))
        self.gridLayout.addWidget(self.pb_getAlias, 14, 1, 1, 1)
        self.pb_getForging = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_getForging.setFont(font)
        self.pb_getForging.setObjectName(_fromUtf8("pb_getForging"))
        self.gridLayout.addWidget(self.pb_getForging, 22, 1, 1, 1)
        self.pb_getGuaranteedBalance = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getGuaranteedBalance.setFont(font)
        self.pb_getGuaranteedBalance.setObjectName(_fromUtf8("pb_getGuaranteedBalance"))
        self.gridLayout.addWidget(self.pb_getGuaranteedBalance, 0, 2, 1, 1)
        self.pb_getMyInfo = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getMyInfo.setFont(font)
        self.pb_getMyInfo.setObjectName(_fromUtf8("pb_getMyInfo"))
        self.gridLayout.addWidget(self.pb_getMyInfo, 1, 2, 1, 1)
        self.pb_getPeer = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getPeer.setFont(font)
        self.pb_getPeer.setObjectName(_fromUtf8("pb_getPeer"))
        self.gridLayout.addWidget(self.pb_getPeer, 2, 2, 1, 1)
        self.pb_getPeers = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getPeers.setFont(font)
        self.pb_getPeers.setObjectName(_fromUtf8("pb_getPeers"))
        self.gridLayout.addWidget(self.pb_getPeers, 3, 2, 1, 1)
        self.pb_getPoll = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getPoll.setFont(font)
        self.pb_getPoll.setObjectName(_fromUtf8("pb_getPoll"))
        self.gridLayout.addWidget(self.pb_getPoll, 4, 2, 1, 1)
        self.pb_getPollIds = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getPollIds.setFont(font)
        self.pb_getPollIds.setObjectName(_fromUtf8("pb_getPollIds"))
        self.gridLayout.addWidget(self.pb_getPollIds, 5, 2, 1, 1)
        self.pb_getState = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getState.setFont(font)
        self.pb_getState.setObjectName(_fromUtf8("pb_getState"))
        self.gridLayout.addWidget(self.pb_getState, 7, 2, 1, 1)
        self.pb_getTime = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getTime.setFont(font)
        self.pb_getTime.setObjectName(_fromUtf8("pb_getTime"))
        self.gridLayout.addWidget(self.pb_getTime, 8, 2, 1, 1)
        self.pb_getTransaction = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getTransaction.setFont(font)
        self.pb_getTransaction.setObjectName(_fromUtf8("pb_getTransaction"))
        self.gridLayout.addWidget(self.pb_getTransaction, 9, 2, 1, 1)
        self.pb_getTransactionBytes = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getTransactionBytes.setFont(font)
        self.pb_getTransactionBytes.setObjectName(_fromUtf8("pb_getTransactionBytes"))
        self.gridLayout.addWidget(self.pb_getTransactionBytes, 10, 2, 1, 1)
        self.pb_getUnconfirmedTransactionIds = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getUnconfirmedTransactionIds.setFont(font)
        self.pb_getUnconfirmedTransactionIds.setObjectName(_fromUtf8("pb_getUnconfirmedTransactionIds"))
        self.gridLayout.addWidget(self.pb_getUnconfirmedTransactionIds, 11, 2, 1, 1)
        self.pb_leaseBalance = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_leaseBalance.setFont(font)
        self.pb_leaseBalance.setObjectName(_fromUtf8("pb_leaseBalance"))
        self.gridLayout.addWidget(self.pb_leaseBalance, 12, 2, 1, 1)
        self.pb_listAccountAliases = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_listAccountAliases.setFont(font)
        self.pb_listAccountAliases.setObjectName(_fromUtf8("pb_listAccountAliases"))
        self.gridLayout.addWidget(self.pb_listAccountAliases, 13, 2, 1, 1)
        self.pb_markHost = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_markHost.setFont(font)
        self.pb_markHost.setObjectName(_fromUtf8("pb_markHost"))
        self.gridLayout.addWidget(self.pb_markHost, 14, 2, 1, 1)
        self.pb_parseTransaction = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_parseTransaction.setFont(font)
        self.pb_parseTransaction.setObjectName(_fromUtf8("pb_parseTransaction"))
        self.gridLayout.addWidget(self.pb_parseTransaction, 16, 2, 1, 1)
        self.pb_signTransaction = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_signTransaction.setFont(font)
        self.pb_signTransaction.setObjectName(_fromUtf8("pb_signTransaction"))
        self.gridLayout.addWidget(self.pb_signTransaction, 20, 2, 1, 1)
        self.tabWidget_querySel.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_2 = QtGui.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(50, 140, 231, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabWidget_querySel.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget_querySel.addTab(self.tab_6, _fromUtf8(""))
        self.lineEdit1_nxtFullQ = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit1_nxtFullQ.setGeometry(QtCore.QRect(90, 830, 1171, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit1_nxtFullQ.setFont(font)
        self.lineEdit1_nxtFullQ.setObjectName(_fromUtf8("lineEdit1_nxtFullQ"))
        self.label_fullQuery = QtGui.QLabel(self.centralwidget)
        self.label_fullQuery.setGeometry(QtCore.QRect(10, 830, 71, 21))
        self.label_fullQuery.setObjectName(_fromUtf8("label_fullQuery"))
        self.pb_sendQuery = QtGui.QPushButton(self.centralwidget)
        self.pb_sendQuery.setGeometry(QtCore.QRect(750, 5, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_sendQuery.setFont(font)
        self.pb_sendQuery.setObjectName(_fromUtf8("pb_sendQuery"))
        self.pb_clearText = QtGui.QPushButton(self.centralwidget)
        self.pb_clearText.setGeometry(QtCore.QRect(985, 10, 101, 31))
        self.pb_clearText.setObjectName(_fromUtf8("pb_clearText"))
        self.cb_scrollCheck = QtGui.QCheckBox(self.centralwidget)
        self.cb_scrollCheck.setGeometry(QtCore.QRect(1190, 50, 71, 22))
        self.cb_scrollCheck.setObjectName(_fromUtf8("cb_scrollCheck"))
        self.lcdNumber_time7 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_time7.setGeometry(QtCore.QRect(1100, 10, 161, 31))
        self.lcdNumber_time7.setObjectName(_fromUtf8("lcdNumber_time7"))
        self.gb_poll7 = QtGui.QGroupBox(self.centralwidget)
        self.gb_poll7.setGeometry(QtCore.QRect(895, 10, 81, 46))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_poll7.setFont(font)
        self.gb_poll7.setCheckable(True)
        self.gb_poll7.setObjectName(_fromUtf8("gb_poll7"))
        self.lineEdit_pollTimer7 = QtGui.QLineEdit(self.gb_poll7)
        self.lineEdit_pollTimer7.setGeometry(QtCore.QRect(25, 24, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_pollTimer7.setFont(font)
        self.lineEdit_pollTimer7.setMaxLength(200)
        self.lineEdit_pollTimer7.setObjectName(_fromUtf8("lineEdit_pollTimer7"))
        self.kled_poll7 = KLed(self.gb_poll7)
        self.kled_poll7.setGeometry(QtCore.QRect(0, 20, 26, 21))
        self.kled_poll7.setColor(QtGui.QColor(0, 10, 250))
        self.kled_poll7.setObjectName(_fromUtf8("kled_poll7"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionMenu = QtGui.QAction(MainWindow)
        self.actionMenu.setObjectName(_fromUtf8("actionMenu"))

        self.retranslateUi(MainWindow)
        self.tabWidget_Req.setCurrentIndex(0)
        self.tabWidget_querySel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "NxtPowerTools Api Access", None))
        self.label_serverAddress.setText(_translate("MainWindow", "server", None))
        self.label_account.setText(_translate("MainWindow", "account", None))
        self.pb_cancelAskOrder.setText(_translate("MainWindow", "cancelAskOrder", None))
        self.pb_getAssetIds.setText(_translate("MainWindow", "getAssetIds", None))
        self.pb_issueAsset.setText(_translate("MainWindow", "issueAsset", None))
        self.pb_getAsset.setText(_translate("MainWindow", "getAsset", None))
        self.pb_cancelBidOrder.setText(_translate("MainWindow", "cancelBidOrder", None))
        self.pb_placeBidOrder.setText(_translate("MainWindow", "placeBidOrder", None))
        self.pb_getAskOrder.setText(_translate("MainWindow", "getAskOrder", None))
        self.pb_getAskOrderIds.setText(_translate("MainWindow", "getAskOrderIds", None))
        self.pb_getBidOrder.setText(_translate("MainWindow", "getBidOrder", None))
        self.pb_getBidOrderIds.setText(_translate("MainWindow", "getBidOrderIds", None))
        self.pb_placeAskOrder.setText(_translate("MainWindow", "placeAskOrder", None))
        self.pb_getAccountCurrentBidOrderIds.setText(_translate("MainWindow", "getAccCurrBidOrderIds", None))
        self.pb_getAccountCurrentAskOrderIds.setText(_translate("MainWindow", "getAccCurrAskOrderIds", None))
        self.pb_transferAsset.setText(_translate("MainWindow", "transferAsset", None))
        self.pb_getAssetsByName.setText(_translate("MainWindow", "getAssetsByName", None))
        self.pb_getAllTrades.setText(_translate("MainWindow", "getAllTrades", None))
        self.pb_getTrades.setText(_translate("MainWindow", "getTrades", None))
        self.pb_getAllOpenOrders.setText(_translate("MainWindow", "getAllOpenOrders", None))
        self.pb_getAllAssets.setText(_translate("MainWindow", "getAllAssets", None))
        self.pb_getAssets.setText(_translate("MainWindow", "getAssets", None))
        self.tabWidget_Req.setTabText(self.tabWidget_Req.indexOf(self.tab), _translate("MainWindow", "nxt requests", None))
        self.label_NXTServer.setText(_translate("MainWindow", "Server", None))
        self.label_NXTServer_2.setText(_translate("MainWindow", "Account", None))
        self.label_passPhrase.setText(_translate("MainWindow", "Pass", None))
        self.label_pubKey.setText(_translate("MainWindow", "PubKey", None))
        self.pb_pullData1.setText(_translate("MainWindow", "pull data from sessMan", None))
        self.tabWidget_Req.setTabText(self.tabWidget_Req.indexOf(self.tab_2), _translate("MainWindow", "sessMan data", None))
        self.label.setText(_translate("MainWindow", "under construction:\n"
"enable log file ", None))
        self.tabWidget_Req.setTabText(self.tabWidget_Req.indexOf(self.tab_3), _translate("MainWindow", "logFile", None))
        self.groupBox.setTitle(_translate("MainWindow", "nxt server reply", None))
        self.pb_getBlock.setText(_translate("MainWindow", "getBlock", None))
        self.pb_sendMoney.setText(_translate("MainWindow", "sendMoney", None))
        self.pb_stopForging.setText(_translate("MainWindow", "stopForging", None))
        self.pb_getAliasIds.setText(_translate("MainWindow", "getAliasIds", None))
        self.pb_getAccountTransactionIds.setText(_translate("MainWindow", "getAccountTransactionIds", None))
        self.pb_setAccountInfo.setText(_translate("MainWindow", "setAccountInfo", None))
        self.pb_getAccount.setText(_translate("MainWindow", "getAccount", None))
        self.pb_getAccountId.setText(_translate("MainWindow", "getAccountId", None))
        self.pb_generateToken.setText(_translate("MainWindow", "generateToken", None))
        self.pb_createPoll.setText(_translate("MainWindow", "createPoll", None))
        self.pb_getAccountPublicKey.setText(_translate("MainWindow", "getAccountPublicKey", None))
        self.pb_getAccountBlockIds.setText(_translate("MainWindow", "getAccountBlockIds", None))
        self.pb_getAliasId.setText(_translate("MainWindow", "getAliasId", None))
        self.pb_assignAlias.setText(_translate("MainWindow", "assignAlias", None))
        self.pb_getBalance.setText(_translate("MainWindow", "getBalance", None))
        self.pb_castVote.setText(_translate("MainWindow", "castVote", None))
        self.pb_broadcastTransaction.setText(_translate("MainWindow", "broadcastTransaction", None))
        self.pb_decodeHallmark.setText(_translate("MainWindow", "decodeHallmark", None))
        self.pb_decodeToken.setText(_translate("MainWindow", "decodeToken", None))
        self.pb_getConstants.setText(_translate("MainWindow", "getConstants", None))
        self.pb_sendMessage.setText(_translate("MainWindow", "sendMessage ", None))
        self.pb_getAliasURI.setText(_translate("MainWindow", "getAliasURI", None))
        self.pb_startForging.setText(_translate("MainWindow", "startForging", None))
        self.pb_getAlias.setText(_translate("MainWindow", "getAlias", None))
        self.pb_getForging.setText(_translate("MainWindow", "getForging", None))
        self.pb_getGuaranteedBalance.setText(_translate("MainWindow", "getGuaranteedBalance", None))
        self.pb_getMyInfo.setText(_translate("MainWindow", "getMyInfo", None))
        self.pb_getPeer.setText(_translate("MainWindow", "getPeer", None))
        self.pb_getPeers.setText(_translate("MainWindow", "getPeers", None))
        self.pb_getPoll.setText(_translate("MainWindow", "getPoll", None))
        self.pb_getPollIds.setText(_translate("MainWindow", "getPollIds", None))
        self.pb_getState.setText(_translate("MainWindow", "getState", None))
        self.pb_getTime.setText(_translate("MainWindow", "getTime", None))
        self.pb_getTransaction.setText(_translate("MainWindow", "getTransaction", None))
        self.pb_getTransactionBytes.setText(_translate("MainWindow", "getTransactionBytes", None))
        self.pb_getUnconfirmedTransactionIds.setText(_translate("MainWindow", "getUnconfTransactionIds", None))
        self.pb_leaseBalance.setText(_translate("MainWindow", "leaseBalance", None))
        self.pb_listAccountAliases.setText(_translate("MainWindow", "listAccountAliases", None))
        self.pb_markHost.setText(_translate("MainWindow", "markHost", None))
        self.pb_parseTransaction.setText(_translate("MainWindow", "parseTransaction", None))
        self.pb_signTransaction.setText(_translate("MainWindow", "signTransaction", None))
        self.tabWidget_querySel.setTabText(self.tabWidget_querySel.indexOf(self.tab_4), _translate("MainWindow", "API CALLS", None))
        self.label_2.setText(_translate("MainWindow", "under construction:\n"
"create Poll", None))
        self.tabWidget_querySel.setTabText(self.tabWidget_querySel.indexOf(self.tab_5), _translate("MainWindow", "create Poll", None))
        self.tabWidget_querySel.setTabText(self.tabWidget_querySel.indexOf(self.tab_6), _translate("MainWindow", "empty", None))
        self.label_fullQuery.setText(_translate("MainWindow", "rawQuery", None))
        self.pb_sendQuery.setText(_translate("MainWindow", "send Query once", None))
        self.pb_clearText.setText(_translate("MainWindow", "clear", None))
        self.cb_scrollCheck.setText(_translate("MainWindow", "scroll", None))
        self.gb_poll7.setTitle(_translate("MainWindow", "Poll", None))
        self.actionMenu.setText(_translate("MainWindow", "menu", None))

from PyKDE4.kdeui import KLed
