# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nxtWin7_h900.ui'
#
# Created: Wed Jul  2 10:58:11 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1280, 880)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1280, 900))
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget_Req = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_Req.setGeometry(QtCore.QRect(380, 0, 366, 821))
        self.tabWidget_Req.setObjectName(_fromUtf8("tabWidget_Req"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 130, 361, 616))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(6, 0, 0, 8)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit1_nxtQ12 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ12.setObjectName(_fromUtf8("lineEdit1_nxtQ12"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ12, 11, 0, 1, 1)
        self.lineEdit1_nxtQ3 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ3.setObjectName(_fromUtf8("lineEdit1_nxtQ3"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ3, 2, 0, 1, 1)
        self.lineEdit1_nxtQ6_Val6 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ6_Val6.setObjectName(_fromUtf8("lineEdit1_nxtQ6_Val6"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ6_Val6, 5, 1, 1, 1)
        self.lineEdit1_nxtQ2 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ2.setObjectName(_fromUtf8("lineEdit1_nxtQ2"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ2, 1, 0, 1, 1)
        self.lineEdit1_nxtQ8_Val8 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ8_Val8.setObjectName(_fromUtf8("lineEdit1_nxtQ8_Val8"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ8_Val8, 7, 1, 1, 1)
        self.lineEdit1_nxtQ5 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ5.setObjectName(_fromUtf8("lineEdit1_nxtQ5"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ5, 4, 0, 1, 1)
        self.lineEdit1_nxtQ7_Val7 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ7_Val7.setObjectName(_fromUtf8("lineEdit1_nxtQ7_Val7"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ7_Val7, 6, 1, 1, 1)
        self.lineEdit1_nxtQ6 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ6.setObjectName(_fromUtf8("lineEdit1_nxtQ6"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ6, 5, 0, 1, 1)
        self.lineEdit1_nxtQ2_Val2 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ2_Val2.setObjectName(_fromUtf8("lineEdit1_nxtQ2_Val2"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ2_Val2, 1, 1, 1, 1)
        self.lineEdit1_nxtQ7 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ7.setObjectName(_fromUtf8("lineEdit1_nxtQ7"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ7, 6, 0, 1, 1)
        self.lineEdit1_nxtQ9_Val9 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ9_Val9.setObjectName(_fromUtf8("lineEdit1_nxtQ9_Val9"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ9_Val9, 8, 1, 1, 1)
        self.lineEdit1_nxtQ3_Val3 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ3_Val3.setObjectName(_fromUtf8("lineEdit1_nxtQ3_Val3"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ3_Val3, 2, 1, 1, 1)
        self.lineEdit1_nxtQ5_Val5 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ5_Val5.setObjectName(_fromUtf8("lineEdit1_nxtQ5_Val5"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ5_Val5, 4, 1, 1, 1)
        self.lineEdit1_nxtQ8 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ8.setObjectName(_fromUtf8("lineEdit1_nxtQ8"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ8, 7, 0, 1, 1)
        self.lineEdit1_nxtQ1_Val1 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ1_Val1.setObjectName(_fromUtf8("lineEdit1_nxtQ1_Val1"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ1_Val1, 0, 1, 1, 1)
        self.lineEdit1_nxtQ1 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ1.setObjectName(_fromUtf8("lineEdit1_nxtQ1"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ1, 0, 0, 1, 1)
        self.lineEdit1_nxtQ9 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ9.setObjectName(_fromUtf8("lineEdit1_nxtQ9"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ9, 8, 0, 1, 1)
        self.lineEdit1_nxtQ4 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ4.setObjectName(_fromUtf8("lineEdit1_nxtQ4"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ4, 3, 0, 1, 1)
        self.lineEdit1_nxtQ4_Val4 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ4_Val4.setObjectName(_fromUtf8("lineEdit1_nxtQ4_Val4"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ4_Val4, 3, 1, 1, 1)
        self.lineEdit1_nxtQ10_Val10 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ10_Val10.setObjectName(_fromUtf8("lineEdit1_nxtQ10_Val10"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ10_Val10, 9, 1, 1, 1)
        self.lineEdit1_nxtQ10 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ10.setObjectName(_fromUtf8("lineEdit1_nxtQ10"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ10, 9, 0, 1, 1)
        self.lineEdit1_nxtQ11 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ11.setObjectName(_fromUtf8("lineEdit1_nxtQ11"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ11, 10, 0, 1, 1)
        self.lineEdit1_nxtQ13 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ13.setObjectName(_fromUtf8("lineEdit1_nxtQ13"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ13, 12, 0, 1, 1)
        self.lineEdit1_nxtQ14 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ14.setObjectName(_fromUtf8("lineEdit1_nxtQ14"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ14, 13, 0, 1, 1)
        self.lineEdit1_nxtQ11_Val11 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ11_Val11.setObjectName(_fromUtf8("lineEdit1_nxtQ11_Val11"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ11_Val11, 10, 1, 1, 1)
        self.lineEdit1_nxtQ12_Val12 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ12_Val12.setObjectName(_fromUtf8("lineEdit1_nxtQ12_Val12"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ12_Val12, 11, 1, 1, 1)
        self.lineEdit1_nxtQ13_Val13 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ13_Val13.setObjectName(_fromUtf8("lineEdit1_nxtQ13_Val13"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ13_Val13, 12, 1, 1, 1)
        self.lineEdit1_nxtQ14_Val14 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1_nxtQ14_Val14.setObjectName(_fromUtf8("lineEdit1_nxtQ14_Val14"))
        self.gridLayout_2.addWidget(self.lineEdit1_nxtQ14_Val14, 13, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.label_serverAddress = QtGui.QLabel(self.tab)
        self.label_serverAddress.setGeometry(QtCore.QRect(0, 5, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_serverAddress.setFont(font)
        self.label_serverAddress.setAlignment(QtCore.Qt.AlignCenter)
        self.label_serverAddress.setObjectName(_fromUtf8("label_serverAddress"))
        self.label_account = QtGui.QLabel(self.tab)
        self.label_account.setGeometry(QtCore.QRect(0, 35, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_account.setFont(font)
        self.label_account.setAlignment(QtCore.Qt.AlignCenter)
        self.label_account.setObjectName(_fromUtf8("label_account"))
        self.lineEdit_account7 = QtGui.QLineEdit(self.tab)
        self.lineEdit_account7.setGeometry(QtCore.QRect(70, 40, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_account7.setFont(font)
        self.lineEdit_account7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_account7.setObjectName(_fromUtf8("lineEdit_account7"))
        self.lineEdit_nxtServer = QtGui.QLineEdit(self.tab)
        self.lineEdit_nxtServer.setGeometry(QtCore.QRect(70, 5, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_nxtServer.setFont(font)
        self.lineEdit_nxtServer.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nxtServer.setObjectName(_fromUtf8("lineEdit_nxtServer"))
        self.tabWidget_Req.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 80, 331, 581))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lineEdit_sessDat1_10 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_10.setFont(font)
        self.lineEdit_sessDat1_10.setMaxLength(2000)
        self.lineEdit_sessDat1_10.setObjectName(_fromUtf8("lineEdit_sessDat1_10"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_10, 13, 1, 1, 1)
        self.lineEdit_sessDat1_14 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_14.setFont(font)
        self.lineEdit_sessDat1_14.setMaxLength(2000)
        self.lineEdit_sessDat1_14.setObjectName(_fromUtf8("lineEdit_sessDat1_14"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_14, 17, 1, 1, 1)
        self.lineEdit_sessDat1 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1.setFont(font)
        self.lineEdit_sessDat1.setMaxLength(2000)
        self.lineEdit_sessDat1.setObjectName(_fromUtf8("lineEdit_sessDat1"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1, 4, 1, 1, 1)
        self.lineEdit_sessDat1_6 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_6.setFont(font)
        self.lineEdit_sessDat1_6.setMaxLength(2000)
        self.lineEdit_sessDat1_6.setObjectName(_fromUtf8("lineEdit_sessDat1_6"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_6, 9, 1, 1, 1)
        self.label_NXTServer = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_NXTServer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NXTServer.setObjectName(_fromUtf8("label_NXTServer"))
        self.gridLayout_6.addWidget(self.label_NXTServer, 0, 0, 1, 1)
        self.lineEdit_passPhr7 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_passPhr7.setFont(font)
        self.lineEdit_passPhr7.setMaxLength(200)
        self.lineEdit_passPhr7.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_passPhr7.setObjectName(_fromUtf8("lineEdit_passPhr7"))
        self.gridLayout_6.addWidget(self.lineEdit_passPhr7, 2, 1, 1, 1)
        self.lineEdit_account1 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_account1.setFont(font)
        self.lineEdit_account1.setMaxLength(200)
        self.lineEdit_account1.setObjectName(_fromUtf8("lineEdit_account1"))
        self.gridLayout_6.addWidget(self.lineEdit_account1, 1, 1, 1, 1)
        self.label_NXTServer_2 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_NXTServer_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NXTServer_2.setObjectName(_fromUtf8("label_NXTServer_2"))
        self.gridLayout_6.addWidget(self.label_NXTServer_2, 1, 0, 1, 1)
        self.label_passPhrase = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_passPhrase.setAlignment(QtCore.Qt.AlignCenter)
        self.label_passPhrase.setObjectName(_fromUtf8("label_passPhrase"))
        self.gridLayout_6.addWidget(self.label_passPhrase, 2, 0, 1, 1)
        self.label_pubKey = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_pubKey.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pubKey.setObjectName(_fromUtf8("label_pubKey"))
        self.gridLayout_6.addWidget(self.label_pubKey, 3, 0, 1, 1)
        self.lineEdit_publicKey1 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_publicKey1.setFont(font)
        self.lineEdit_publicKey1.setMaxLength(2000)
        self.lineEdit_publicKey1.setObjectName(_fromUtf8("lineEdit_publicKey1"))
        self.gridLayout_6.addWidget(self.lineEdit_publicKey1, 3, 1, 1, 1)
        self.lineEdit_nxtServer1 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_nxtServer1.setFont(font)
        self.lineEdit_nxtServer1.setMaxLength(200)
        self.lineEdit_nxtServer1.setObjectName(_fromUtf8("lineEdit_nxtServer1"))
        self.gridLayout_6.addWidget(self.lineEdit_nxtServer1, 0, 1, 1, 1)
        self.lineEdit_sessDat1_4 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_4.setFont(font)
        self.lineEdit_sessDat1_4.setMaxLength(2000)
        self.lineEdit_sessDat1_4.setObjectName(_fromUtf8("lineEdit_sessDat1_4"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_4, 7, 1, 1, 1)
        self.lineEdit_sessDat1_8 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_8.setFont(font)
        self.lineEdit_sessDat1_8.setMaxLength(2000)
        self.lineEdit_sessDat1_8.setObjectName(_fromUtf8("lineEdit_sessDat1_8"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_8, 11, 1, 1, 1)
        self.lineEdit_sessDat1_12 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_12.setFont(font)
        self.lineEdit_sessDat1_12.setMaxLength(2000)
        self.lineEdit_sessDat1_12.setObjectName(_fromUtf8("lineEdit_sessDat1_12"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_12, 15, 1, 1, 1)
        self.lineEdit_sessDat1_2 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_2.setFont(font)
        self.lineEdit_sessDat1_2.setMaxLength(2000)
        self.lineEdit_sessDat1_2.setObjectName(_fromUtf8("lineEdit_sessDat1_2"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_2, 5, 1, 1, 1)
        self.lineEdit_sessDat1_13 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_13.setFont(font)
        self.lineEdit_sessDat1_13.setMaxLength(2000)
        self.lineEdit_sessDat1_13.setObjectName(_fromUtf8("lineEdit_sessDat1_13"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_13, 16, 1, 1, 1)
        self.lineEdit_sessDat1_7 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_7.setFont(font)
        self.lineEdit_sessDat1_7.setMaxLength(2000)
        self.lineEdit_sessDat1_7.setObjectName(_fromUtf8("lineEdit_sessDat1_7"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_7, 10, 1, 1, 1)
        self.lineEdit_sessDat1_9 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_9.setFont(font)
        self.lineEdit_sessDat1_9.setMaxLength(2000)
        self.lineEdit_sessDat1_9.setObjectName(_fromUtf8("lineEdit_sessDat1_9"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_9, 12, 1, 1, 1)
        self.lineEdit_sessDat1_11 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_11.setFont(font)
        self.lineEdit_sessDat1_11.setMaxLength(2000)
        self.lineEdit_sessDat1_11.setObjectName(_fromUtf8("lineEdit_sessDat1_11"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_11, 14, 1, 1, 1)
        self.lineEdit_sessDat1_3 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_3.setFont(font)
        self.lineEdit_sessDat1_3.setMaxLength(2000)
        self.lineEdit_sessDat1_3.setObjectName(_fromUtf8("lineEdit_sessDat1_3"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_3, 6, 1, 1, 1)
        self.lineEdit_sessDat1_5 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_5.setFont(font)
        self.lineEdit_sessDat1_5.setMaxLength(2000)
        self.lineEdit_sessDat1_5.setObjectName(_fromUtf8("lineEdit_sessDat1_5"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_5, 8, 1, 1, 1)
        self.lineEdit_sessDat1_15 = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_sessDat1_15.setFont(font)
        self.lineEdit_sessDat1_15.setMaxLength(2000)
        self.lineEdit_sessDat1_15.setObjectName(_fromUtf8("lineEdit_sessDat1_15"))
        self.gridLayout_6.addWidget(self.lineEdit_sessDat1_15, 18, 1, 1, 1)
        self.pb_pullData1 = QtGui.QPushButton(self.tab_2)
        self.pb_pullData1.setGeometry(QtCore.QRect(150, 40, 181, 31))
        self.pb_pullData1.setObjectName(_fromUtf8("pb_pullData1"))
        self.tabWidget_Req.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget_Req.addTab(self.tab_3, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(750, 65, 521, 756))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.textEdit_NRSRaw1 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_NRSRaw1.setGeometry(QtCore.QRect(5, 20, 516, 731))
        self.textEdit_NRSRaw1.setReadOnly(True)
        self.textEdit_NRSRaw1.setObjectName(_fromUtf8("textEdit_NRSRaw1"))
        self.tabWidget_querySel = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_querySel.setGeometry(QtCore.QRect(0, -5, 381, 826))
        self.tabWidget_querySel.setObjectName(_fromUtf8("tabWidget_querySel"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 50, 351, 426))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pb_getConstants = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getConstants.setFont(font)
        self.pb_getConstants.setObjectName(_fromUtf8("pb_getConstants"))
        self.gridLayout.addWidget(self.pb_getConstants, 2, 1, 1, 1)
        self.pb_decodeToken = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_decodeToken.setFont(font)
        self.pb_decodeToken.setObjectName(_fromUtf8("pb_decodeToken"))
        self.gridLayout.addWidget(self.pb_decodeToken, 4, 1, 1, 1)
        self.pb_getBlockId = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getBlockId.setFont(font)
        self.pb_getBlockId.setObjectName(_fromUtf8("pb_getBlockId"))
        self.gridLayout.addWidget(self.pb_getBlockId, 1, 1, 1, 1)
        self.pb_getBlock = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getBlock.setFont(font)
        self.pb_getBlock.setObjectName(_fromUtf8("pb_getBlock"))
        self.gridLayout.addWidget(self.pb_getBlock, 0, 2, 1, 1)
        self.pb_broadcastTransaction = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_broadcastTransaction.setFont(font)
        self.pb_broadcastTransaction.setObjectName(_fromUtf8("pb_broadcastTransaction"))
        self.gridLayout.addWidget(self.pb_broadcastTransaction, 0, 1, 1, 1)
        self.pb_getPeer = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getPeer.setFont(font)
        self.pb_getPeer.setObjectName(_fromUtf8("pb_getPeer"))
        self.gridLayout.addWidget(self.pb_getPeer, 3, 2, 1, 1)
        self.pb_getPeers = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getPeers.setFont(font)
        self.pb_getPeers.setObjectName(_fromUtf8("pb_getPeers"))
        self.gridLayout.addWidget(self.pb_getPeers, 4, 2, 1, 1)
        self.pb_getUnconfirmedTransactionIds = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getUnconfirmedTransactionIds.setFont(font)
        self.pb_getUnconfirmedTransactionIds.setObjectName(_fromUtf8("pb_getUnconfirmedTransactionIds"))
        self.gridLayout.addWidget(self.pb_getUnconfirmedTransactionIds, 14, 2, 1, 1)
        self.pb_decodeHallmark = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_decodeHallmark.setFont(font)
        self.pb_decodeHallmark.setObjectName(_fromUtf8("pb_decodeHallmark"))
        self.gridLayout.addWidget(self.pb_decodeHallmark, 3, 1, 1, 1)
        self.pb_calculateFullHash = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_calculateFullHash.setFont(font)
        self.pb_calculateFullHash.setObjectName(_fromUtf8("pb_calculateFullHash"))
        self.gridLayout.addWidget(self.pb_calculateFullHash, 5, 1, 1, 1)
        self.pb_markHost = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_markHost.setFont(font)
        self.pb_markHost.setObjectName(_fromUtf8("pb_markHost"))
        self.gridLayout.addWidget(self.pb_markHost, 5, 2, 1, 1)
        self.pb_getBlockchainStatus = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getBlockchainStatus.setFont(font)
        self.pb_getBlockchainStatus.setObjectName(_fromUtf8("pb_getBlockchainStatus"))
        self.gridLayout.addWidget(self.pb_getBlockchainStatus, 1, 2, 1, 1)
        self.pb_getState = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getState.setFont(font)
        self.pb_getState.setObjectName(_fromUtf8("pb_getState"))
        self.gridLayout.addWidget(self.pb_getState, 6, 1, 1, 1)
        self.pb_getTime = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getTime.setFont(font)
        self.pb_getTime.setObjectName(_fromUtf8("pb_getTime"))
        self.gridLayout.addWidget(self.pb_getTime, 6, 2, 1, 1)
        self.pb_getTransactionBytes = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getTransactionBytes.setFont(font)
        self.pb_getTransactionBytes.setObjectName(_fromUtf8("pb_getTransactionBytes"))
        self.gridLayout.addWidget(self.pb_getTransactionBytes, 7, 2, 1, 1)
        self.pb_getTransaction = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getTransaction.setFont(font)
        self.pb_getTransaction.setObjectName(_fromUtf8("pb_getTransaction"))
        self.gridLayout.addWidget(self.pb_getTransaction, 7, 1, 1, 1)
        self.pb_getUnconfirmedTransactions = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getUnconfirmedTransactions.setFont(font)
        self.pb_getUnconfirmedTransactions.setObjectName(_fromUtf8("pb_getUnconfirmedTransactions"))
        self.gridLayout.addWidget(self.pb_getUnconfirmedTransactions, 14, 1, 1, 1)
        self.pb_parseTransaction = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_parseTransaction.setFont(font)
        self.pb_parseTransaction.setObjectName(_fromUtf8("pb_parseTransaction"))
        self.gridLayout.addWidget(self.pb_parseTransaction, 13, 2, 1, 1)
        self.pb_getNextBlockGenerators = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getNextBlockGenerators.setFont(font)
        self.pb_getNextBlockGenerators.setObjectName(_fromUtf8("pb_getNextBlockGenerators"))
        self.gridLayout.addWidget(self.pb_getNextBlockGenerators, 2, 2, 1, 1)
        self.pb_getMyInfo = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getMyInfo.setFont(font)
        self.pb_getMyInfo.setObjectName(_fromUtf8("pb_getMyInfo"))
        self.gridLayout.addWidget(self.pb_getMyInfo, 13, 1, 1, 1)
        self.tabWidget_querySel.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tab_5)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(25, 525, 311, 121))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pb_sendMessage = QtGui.QPushButton(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_sendMessage.setFont(font)
        self.pb_sendMessage.setObjectName(_fromUtf8("pb_sendMessage"))
        self.gridLayout_7.addWidget(self.pb_sendMessage, 1, 0, 1, 1)
        self.pb_encryptTo = QtGui.QPushButton(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_encryptTo.setFont(font)
        self.pb_encryptTo.setObjectName(_fromUtf8("pb_encryptTo"))
        self.gridLayout_7.addWidget(self.pb_encryptTo, 2, 1, 1, 1)
        self.pb_decryptFrom = QtGui.QPushButton(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_decryptFrom.setFont(font)
        self.pb_decryptFrom.setObjectName(_fromUtf8("pb_decryptFrom"))
        self.gridLayout_7.addWidget(self.pb_decryptFrom, 2, 0, 1, 1)
        self.pb_sendEncryptedNote = QtGui.QPushButton(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_sendEncryptedNote.setFont(font)
        self.pb_sendEncryptedNote.setObjectName(_fromUtf8("pb_sendEncryptedNote"))
        self.gridLayout_7.addWidget(self.pb_sendEncryptedNote, 1, 1, 1, 1)
        self.pb_readEncryptedNote = QtGui.QPushButton(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_readEncryptedNote.setFont(font)
        self.pb_readEncryptedNote.setObjectName(_fromUtf8("pb_readEncryptedNote"))
        self.gridLayout_7.addWidget(self.pb_readEncryptedNote, 0, 0, 1, 1)
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tab_5)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(40, 670, 281, 101))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pb_getPoll = QtGui.QPushButton(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getPoll.setFont(font)
        self.pb_getPoll.setObjectName(_fromUtf8("pb_getPoll"))
        self.gridLayout_5.addWidget(self.pb_getPoll, 2, 0, 1, 1)
        self.pb_castVote = QtGui.QPushButton(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_castVote.setFont(font)
        self.pb_castVote.setObjectName(_fromUtf8("pb_castVote"))
        self.gridLayout_5.addWidget(self.pb_castVote, 1, 0, 1, 1)
        self.pb_getPollIds = QtGui.QPushButton(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getPollIds.setFont(font)
        self.pb_getPollIds.setObjectName(_fromUtf8("pb_getPollIds"))
        self.gridLayout_5.addWidget(self.pb_getPollIds, 1, 1, 1, 1)
        self.pb_createPoll = QtGui.QPushButton(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_createPoll.setFont(font)
        self.pb_createPoll.setObjectName(_fromUtf8("pb_createPoll"))
        self.gridLayout_5.addWidget(self.pb_createPoll, 2, 1, 1, 1)
        self.gridLayoutWidget_8 = QtGui.QWidget(self.tab_5)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(5, 10, 356, 356))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.pb_stopForging = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_stopForging.setFont(font)
        self.pb_stopForging.setObjectName(_fromUtf8("pb_stopForging"))
        self.gridLayout_8.addWidget(self.pb_stopForging, 7, 0, 1, 1)
        self.pb_leaseBalance = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_leaseBalance.setFont(font)
        self.pb_leaseBalance.setObjectName(_fromUtf8("pb_leaseBalance"))
        self.gridLayout_8.addWidget(self.pb_leaseBalance, 4, 0, 1, 1)
        self.pb_getForging = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_getForging.setFont(font)
        self.pb_getForging.setObjectName(_fromUtf8("pb_getForging"))
        self.gridLayout_8.addWidget(self.pb_getForging, 5, 0, 1, 1)
        self.pb_signTransaction = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_signTransaction.setFont(font)
        self.pb_signTransaction.setObjectName(_fromUtf8("pb_signTransaction"))
        self.gridLayout_8.addWidget(self.pb_signTransaction, 8, 0, 1, 1)
        self.pb_getAccountBlockIds = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_getAccountBlockIds.setFont(font)
        self.pb_getAccountBlockIds.setObjectName(_fromUtf8("pb_getAccountBlockIds"))
        self.gridLayout_8.addWidget(self.pb_getAccountBlockIds, 0, 1, 1, 1)
        self.pb_getAccountId = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_getAccountId.setFont(font)
        self.pb_getAccountId.setObjectName(_fromUtf8("pb_getAccountId"))
        self.gridLayout_8.addWidget(self.pb_getAccountId, 1, 0, 1, 1)
        self.pb_getAccount = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_getAccount.setFont(font)
        self.pb_getAccount.setObjectName(_fromUtf8("pb_getAccount"))
        self.gridLayout_8.addWidget(self.pb_getAccount, 0, 0, 1, 1)
        self.pb_getAccountTransactionIds = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAccountTransactionIds.setFont(font)
        self.pb_getAccountTransactionIds.setObjectName(_fromUtf8("pb_getAccountTransactionIds"))
        self.gridLayout_8.addWidget(self.pb_getAccountTransactionIds, 2, 0, 1, 1)
        self.pb_getAccountPublicKey = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAccountPublicKey.setFont(font)
        self.pb_getAccountPublicKey.setObjectName(_fromUtf8("pb_getAccountPublicKey"))
        self.gridLayout_8.addWidget(self.pb_getAccountPublicKey, 1, 1, 1, 1)
        self.pb_sendMoney = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_sendMoney.setFont(font)
        self.pb_sendMoney.setObjectName(_fromUtf8("pb_sendMoney"))
        self.gridLayout_8.addWidget(self.pb_sendMoney, 9, 0, 1, 1)
        self.pb_getBalance = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getBalance.setFont(font)
        self.pb_getBalance.setObjectName(_fromUtf8("pb_getBalance"))
        self.gridLayout_8.addWidget(self.pb_getBalance, 4, 1, 1, 1)
        self.pb_rsConvert = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_rsConvert.setFont(font)
        self.pb_rsConvert.setObjectName(_fromUtf8("pb_rsConvert"))
        self.gridLayout_8.addWidget(self.pb_rsConvert, 9, 1, 1, 1)
        self.pb_setAccountInfo = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_setAccountInfo.setFont(font)
        self.pb_setAccountInfo.setObjectName(_fromUtf8("pb_setAccountInfo"))
        self.gridLayout_8.addWidget(self.pb_setAccountInfo, 2, 1, 1, 1)
        self.pb_startForging = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_startForging.setFont(font)
        self.pb_startForging.setObjectName(_fromUtf8("pb_startForging"))
        self.gridLayout_8.addWidget(self.pb_startForging, 5, 1, 1, 1)
        self.pb_getGuaranteedBalance = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getGuaranteedBalance.setFont(font)
        self.pb_getGuaranteedBalance.setObjectName(_fromUtf8("pb_getGuaranteedBalance"))
        self.gridLayout_8.addWidget(self.pb_getGuaranteedBalance, 7, 1, 1, 1)
        self.pb_generateToken = QtGui.QPushButton(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_generateToken.setFont(font)
        self.pb_generateToken.setObjectName(_fromUtf8("pb_generateToken"))
        self.gridLayout_8.addWidget(self.pb_generateToken, 8, 1, 1, 1)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tab_5)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(50, 380, 251, 111))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pb_getAliases = QtGui.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAliases.setFont(font)
        self.pb_getAliases.setObjectName(_fromUtf8("pb_getAliases"))
        self.gridLayout_4.addWidget(self.pb_getAliases, 1, 1, 1, 1)
        self.pb_getAlias = QtGui.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAlias.setFont(font)
        self.pb_getAlias.setObjectName(_fromUtf8("pb_getAlias"))
        self.gridLayout_4.addWidget(self.pb_getAlias, 0, 1, 1, 1)
        self.pb_buyAlias = QtGui.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_buyAlias.setFont(font)
        self.pb_buyAlias.setObjectName(_fromUtf8("pb_buyAlias"))
        self.gridLayout_4.addWidget(self.pb_buyAlias, 0, 0, 1, 1)
        self.pb_sellAlias = QtGui.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_sellAlias.setFont(font)
        self.pb_sellAlias.setObjectName(_fromUtf8("pb_sellAlias"))
        self.gridLayout_4.addWidget(self.pb_sellAlias, 1, 0, 1, 1)
        self.pb_setAlias = QtGui.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_setAlias.setFont(font)
        self.pb_setAlias.setObjectName(_fromUtf8("pb_setAlias"))
        self.gridLayout_4.addWidget(self.pb_setAlias, 2, 0, 1, 1)
        self.tabWidget_querySel.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_6)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 350, 351, 425))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pb_getBidOrderIds = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getBidOrderIds.setFont(font)
        self.pb_getBidOrderIds.setObjectName(_fromUtf8("pb_getBidOrderIds"))
        self.gridLayout_3.addWidget(self.pb_getBidOrderIds, 13, 1, 1, 1)
        self.pb_cancelAskOrder = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_cancelAskOrder.setFont(font)
        self.pb_cancelAskOrder.setObjectName(_fromUtf8("pb_cancelAskOrder"))
        self.gridLayout_3.addWidget(self.pb_cancelAskOrder, 12, 0, 1, 1)
        self.pb_cancelBidOrder = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_cancelBidOrder.setFont(font)
        self.pb_cancelBidOrder.setObjectName(_fromUtf8("pb_cancelBidOrder"))
        self.gridLayout_3.addWidget(self.pb_cancelBidOrder, 12, 1, 1, 1)
        self.pb_placeBidOrder = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_placeBidOrder.setFont(font)
        self.pb_placeBidOrder.setObjectName(_fromUtf8("pb_placeBidOrder"))
        self.gridLayout_3.addWidget(self.pb_placeBidOrder, 11, 1, 1, 1)
        self.pb_getAskOrder = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAskOrder.setFont(font)
        self.pb_getAskOrder.setObjectName(_fromUtf8("pb_getAskOrder"))
        self.gridLayout_3.addWidget(self.pb_getAskOrder, 14, 0, 1, 1)
        self.pb_getAskOrderIds = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAskOrderIds.setFont(font)
        self.pb_getAskOrderIds.setObjectName(_fromUtf8("pb_getAskOrderIds"))
        self.gridLayout_3.addWidget(self.pb_getAskOrderIds, 13, 0, 1, 1)
        self.pb_getBidOrder = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getBidOrder.setFont(font)
        self.pb_getBidOrder.setObjectName(_fromUtf8("pb_getBidOrder"))
        self.gridLayout_3.addWidget(self.pb_getBidOrder, 14, 1, 1, 1)
        self.pb_placeAskOrder = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_placeAskOrder.setFont(font)
        self.pb_placeAskOrder.setObjectName(_fromUtf8("pb_placeAskOrder"))
        self.gridLayout_3.addWidget(self.pb_placeAskOrder, 11, 0, 1, 1)
        self.pb_getAccountCurrentBidOrderIds = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAccountCurrentBidOrderIds.setFont(font)
        self.pb_getAccountCurrentBidOrderIds.setObjectName(_fromUtf8("pb_getAccountCurrentBidOrderIds"))
        self.gridLayout_3.addWidget(self.pb_getAccountCurrentBidOrderIds, 10, 1, 1, 1)
        self.pb_getAccountCurrentAskOrderIds = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAccountCurrentAskOrderIds.setFont(font)
        self.pb_getAccountCurrentAskOrderIds.setObjectName(_fromUtf8("pb_getAccountCurrentAskOrderIds"))
        self.gridLayout_3.addWidget(self.pb_getAccountCurrentAskOrderIds, 10, 0, 1, 1)
        self.pb_transferAsset = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_transferAsset.setFont(font)
        self.pb_transferAsset.setObjectName(_fromUtf8("pb_transferAsset"))
        self.gridLayout_3.addWidget(self.pb_transferAsset, 2, 1, 1, 1)
        self.pb_getTrades = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_getTrades.setFont(font)
        self.pb_getTrades.setObjectName(_fromUtf8("pb_getTrades"))
        self.gridLayout_3.addWidget(self.pb_getTrades, 7, 0, 1, 1)
        self.pb_getAssets = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAssets.setFont(font)
        self.pb_getAssets.setObjectName(_fromUtf8("pb_getAssets"))
        self.gridLayout_3.addWidget(self.pb_getAssets, 5, 1, 1, 1)
        self.pb_getAllOpenOrders = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAllOpenOrders.setFont(font)
        self.pb_getAllOpenOrders.setObjectName(_fromUtf8("pb_getAllOpenOrders"))
        self.gridLayout_3.addWidget(self.pb_getAllOpenOrders, 0, 1, 1, 1)
        self.pb_getAllAssets = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAllAssets.setFont(font)
        self.pb_getAllAssets.setObjectName(_fromUtf8("pb_getAllAssets"))
        self.gridLayout_3.addWidget(self.pb_getAllAssets, 0, 0, 1, 1)
        self.pb_getAskOrders = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAskOrders.setFont(font)
        self.pb_getAskOrders.setObjectName(_fromUtf8("pb_getAskOrders"))
        self.gridLayout_3.addWidget(self.pb_getAskOrders, 15, 0, 1, 1)
        self.pb_getBidOrders = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getBidOrders.setFont(font)
        self.pb_getBidOrders.setObjectName(_fromUtf8("pb_getBidOrders"))
        self.gridLayout_3.addWidget(self.pb_getBidOrders, 15, 1, 1, 1)
        self.pb_getAssetIds = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAssetIds.setFont(font)
        self.pb_getAssetIds.setObjectName(_fromUtf8("pb_getAssetIds"))
        self.gridLayout_3.addWidget(self.pb_getAssetIds, 4, 1, 1, 1)
        self.pb_getAssetsByIssuer = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAssetsByIssuer.setFont(font)
        self.pb_getAssetsByIssuer.setObjectName(_fromUtf8("pb_getAssetsByIssuer"))
        self.gridLayout_3.addWidget(self.pb_getAssetsByIssuer, 7, 1, 1, 1)
        self.pb_getAsset = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAsset.setFont(font)
        self.pb_getAsset.setObjectName(_fromUtf8("pb_getAsset"))
        self.gridLayout_3.addWidget(self.pb_getAsset, 5, 0, 1, 1)
        self.pb_issueAsset = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_issueAsset.setFont(font)
        self.pb_issueAsset.setObjectName(_fromUtf8("pb_issueAsset"))
        self.gridLayout_3.addWidget(self.pb_issueAsset, 4, 0, 1, 1)
        self.pb_getAllTrades = QtGui.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pb_getAllTrades.setFont(font)
        self.pb_getAllTrades.setObjectName(_fromUtf8("pb_getAllTrades"))
        self.gridLayout_3.addWidget(self.pb_getAllTrades, 2, 0, 1, 1)
        self.gridLayoutWidget_9 = QtGui.QWidget(self.tab_6)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(5, 40, 366, 271))
        self.gridLayoutWidget_9.setObjectName(_fromUtf8("gridLayoutWidget_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.pb_dgsPriceChange = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_dgsPriceChange.setFont(font)
        self.pb_dgsPriceChange.setObjectName(_fromUtf8("pb_dgsPriceChange"))
        self.gridLayout_9.addWidget(self.pb_dgsPriceChange, 5, 0, 1, 1)
        self.pb_getDGSPurchase = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getDGSPurchase.setFont(font)
        self.pb_getDGSPurchase.setObjectName(_fromUtf8("pb_getDGSPurchase"))
        self.gridLayout_9.addWidget(self.pb_getDGSPurchase, 1, 2, 1, 1)
        self.pb_dgsFeedback = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_dgsFeedback.setFont(font)
        self.pb_dgsFeedback.setObjectName(_fromUtf8("pb_dgsFeedback"))
        self.gridLayout_9.addWidget(self.pb_dgsFeedback, 4, 0, 1, 1)
        self.pb_dgsQuantityChange = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_dgsQuantityChange.setFont(font)
        self.pb_dgsQuantityChange.setObjectName(_fromUtf8("pb_dgsQuantityChange"))
        self.gridLayout_9.addWidget(self.pb_dgsQuantityChange, 6, 0, 1, 1)
        self.pb_getDGSPendingPurchases = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getDGSPendingPurchases.setFont(font)
        self.pb_getDGSPendingPurchases.setObjectName(_fromUtf8("pb_getDGSPendingPurchases"))
        self.gridLayout_9.addWidget(self.pb_getDGSPendingPurchases, 1, 0, 1, 1)
        self.pb_dgsDelisting = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_dgsDelisting.setFont(font)
        self.pb_dgsDelisting.setObjectName(_fromUtf8("pb_dgsDelisting"))
        self.gridLayout_9.addWidget(self.pb_dgsDelisting, 3, 0, 1, 1)
        self.pb_dgsListing = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_dgsListing.setFont(font)
        self.pb_dgsListing.setObjectName(_fromUtf8("pb_dgsListing"))
        self.gridLayout_9.addWidget(self.pb_dgsListing, 4, 2, 1, 1)
        self.pb_dgsPurchase = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_dgsPurchase.setFont(font)
        self.pb_dgsPurchase.setObjectName(_fromUtf8("pb_dgsPurchase"))
        self.gridLayout_9.addWidget(self.pb_dgsPurchase, 5, 2, 1, 1)
        self.pb_dgsDelivery = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_dgsDelivery.setFont(font)
        self.pb_dgsDelivery.setObjectName(_fromUtf8("pb_dgsDelivery"))
        self.gridLayout_9.addWidget(self.pb_dgsDelivery, 3, 2, 1, 1)
        self.pb_dgsRefund = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_dgsRefund.setFont(font)
        self.pb_dgsRefund.setObjectName(_fromUtf8("pb_dgsRefund"))
        self.gridLayout_9.addWidget(self.pb_dgsRefund, 6, 2, 1, 1)
        self.pb_getDGSGoods = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getDGSGoods.setFont(font)
        self.pb_getDGSGoods.setObjectName(_fromUtf8("pb_getDGSGoods"))
        self.gridLayout_9.addWidget(self.pb_getDGSGoods, 0, 2, 1, 1)
        self.pb_getDGSGood = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getDGSGood.setFont(font)
        self.pb_getDGSGood.setObjectName(_fromUtf8("pb_getDGSGood"))
        self.gridLayout_9.addWidget(self.pb_getDGSGood, 0, 0, 1, 1)
        self.pb_getDGSPurchases = QtGui.QPushButton(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pb_getDGSPurchases.setFont(font)
        self.pb_getDGSPurchases.setObjectName(_fromUtf8("pb_getDGSPurchases"))
        self.gridLayout_9.addWidget(self.pb_getDGSPurchases, 2, 0, 1, 1)
        self.tabWidget_querySel.addTab(self.tab_6, _fromUtf8(""))
        self.lineEdit1_nxtFullQ = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit1_nxtFullQ.setGeometry(QtCore.QRect(90, 830, 1171, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit1_nxtFullQ.setFont(font)
        self.lineEdit1_nxtFullQ.setObjectName(_fromUtf8("lineEdit1_nxtFullQ"))
        self.label_fullQuery = QtGui.QLabel(self.centralwidget)
        self.label_fullQuery.setGeometry(QtCore.QRect(10, 830, 71, 21))
        self.label_fullQuery.setObjectName(_fromUtf8("label_fullQuery"))
        self.pb_sendQuery = QtGui.QPushButton(self.centralwidget)
        self.pb_sendQuery.setGeometry(QtCore.QRect(750, 5, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_sendQuery.setFont(font)
        self.pb_sendQuery.setObjectName(_fromUtf8("pb_sendQuery"))
        self.pb_clearText = QtGui.QPushButton(self.centralwidget)
        self.pb_clearText.setGeometry(QtCore.QRect(985, 10, 101, 31))
        self.pb_clearText.setObjectName(_fromUtf8("pb_clearText"))
        self.cb_scrollCheck = QtGui.QCheckBox(self.centralwidget)
        self.cb_scrollCheck.setGeometry(QtCore.QRect(1190, 50, 71, 22))
        self.cb_scrollCheck.setObjectName(_fromUtf8("cb_scrollCheck"))
        self.lcdNumber_time7 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_time7.setGeometry(QtCore.QRect(1100, 10, 161, 31))
        self.lcdNumber_time7.setObjectName(_fromUtf8("lcdNumber_time7"))
        self.gb_poll7 = QtGui.QGroupBox(self.centralwidget)
        self.gb_poll7.setGeometry(QtCore.QRect(895, 10, 81, 46))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_poll7.setFont(font)
        self.gb_poll7.setCheckable(True)
        self.gb_poll7.setObjectName(_fromUtf8("gb_poll7"))
        self.lineEdit_pollTimer7 = QtGui.QLineEdit(self.gb_poll7)
        self.lineEdit_pollTimer7.setGeometry(QtCore.QRect(25, 24, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_pollTimer7.setFont(font)
        self.lineEdit_pollTimer7.setMaxLength(200)
        self.lineEdit_pollTimer7.setObjectName(_fromUtf8("lineEdit_pollTimer7"))
        self.kled_poll7 = KLed(self.gb_poll7)
        self.kled_poll7.setGeometry(QtCore.QRect(0, 20, 26, 21))
        self.kled_poll7.setColor(QtGui.QColor(0, 10, 250))
        self.kled_poll7.setObjectName(_fromUtf8("kled_poll7"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionMenu = QtGui.QAction(MainWindow)
        self.actionMenu.setObjectName(_fromUtf8("actionMenu"))

        self.retranslateUi(MainWindow)
        self.tabWidget_Req.setCurrentIndex(0)
        self.tabWidget_querySel.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "NxtPowerTools Api Access", None))
        self.label_serverAddress.setText(_translate("MainWindow", "server", None))
        self.label_account.setText(_translate("MainWindow", "account", None))
        self.tabWidget_Req.setTabText(self.tabWidget_Req.indexOf(self.tab), _translate("MainWindow", "nxt requests", None))
        self.label_NXTServer.setText(_translate("MainWindow", "Server", None))
        self.label_NXTServer_2.setText(_translate("MainWindow", "Account", None))
        self.label_passPhrase.setText(_translate("MainWindow", "Pass", None))
        self.label_pubKey.setText(_translate("MainWindow", "PubKey", None))
        self.pb_pullData1.setText(_translate("MainWindow", "pull data from sessMan", None))
        self.tabWidget_Req.setTabText(self.tabWidget_Req.indexOf(self.tab_2), _translate("MainWindow", "sessMan data", None))
        self.tabWidget_Req.setTabText(self.tabWidget_Req.indexOf(self.tab_3), _translate("MainWindow", "logFile", None))
        self.groupBox.setTitle(_translate("MainWindow", "nxt server reply", None))
        self.pb_getConstants.setText(_translate("MainWindow", "getConstants", None))
        self.pb_decodeToken.setText(_translate("MainWindow", "decodeToken", None))
        self.pb_getBlockId.setText(_translate("MainWindow", "getBlockId", None))
        self.pb_getBlock.setText(_translate("MainWindow", "getBlock", None))
        self.pb_broadcastTransaction.setText(_translate("MainWindow", "broadcastTransaction", None))
        self.pb_getPeer.setText(_translate("MainWindow", "getPeer", None))
        self.pb_getPeers.setText(_translate("MainWindow", "getPeers", None))
        self.pb_getUnconfirmedTransactionIds.setText(_translate("MainWindow", "getUnconfTransactionIds", None))
        self.pb_decodeHallmark.setText(_translate("MainWindow", "decodeHallmark", None))
        self.pb_calculateFullHash.setText(_translate("MainWindow", "calculateFullHash", None))
        self.pb_markHost.setText(_translate("MainWindow", "markHost", None))
        self.pb_getBlockchainStatus.setText(_translate("MainWindow", "getBlockchainStatus", None))
        self.pb_getState.setText(_translate("MainWindow", "getState", None))
        self.pb_getTime.setText(_translate("MainWindow", "getTime", None))
        self.pb_getTransactionBytes.setText(_translate("MainWindow", "getTransactionBytes", None))
        self.pb_getTransaction.setText(_translate("MainWindow", "getTransaction", None))
        self.pb_getUnconfirmedTransactions.setText(_translate("MainWindow", "getUnconfTransactions", None))
        self.pb_parseTransaction.setText(_translate("MainWindow", "parseTransaction", None))
        self.pb_getNextBlockGenerators.setText(_translate("MainWindow", "getNextBlockGenerators", None))
        self.pb_getMyInfo.setText(_translate("MainWindow", "getMyInfo", None))
        self.tabWidget_querySel.setTabText(self.tabWidget_querySel.indexOf(self.tab_4), _translate("MainWindow", "NXT", None))
        self.pb_sendMessage.setText(_translate("MainWindow", "sendMessage ", None))
        self.pb_encryptTo.setText(_translate("MainWindow", "encryptTo", None))
        self.pb_decryptFrom.setText(_translate("MainWindow", "decryptFrom", None))
        self.pb_sendEncryptedNote.setText(_translate("MainWindow", "sendEncryptedNote", None))
        self.pb_readEncryptedNote.setText(_translate("MainWindow", "readEncryptedNote", None))
        self.pb_getPoll.setText(_translate("MainWindow", "getPoll", None))
        self.pb_castVote.setText(_translate("MainWindow", "castVote", None))
        self.pb_getPollIds.setText(_translate("MainWindow", "getPollIds", None))
        self.pb_createPoll.setText(_translate("MainWindow", "createPoll", None))
        self.pb_stopForging.setText(_translate("MainWindow", "stopForging", None))
        self.pb_leaseBalance.setText(_translate("MainWindow", "leaseBalance", None))
        self.pb_getForging.setText(_translate("MainWindow", "getForging", None))
        self.pb_signTransaction.setText(_translate("MainWindow", "signTransaction", None))
        self.pb_getAccountBlockIds.setText(_translate("MainWindow", "getAccountBlockIds", None))
        self.pb_getAccountId.setText(_translate("MainWindow", "getAccountId", None))
        self.pb_getAccount.setText(_translate("MainWindow", "getAccount", None))
        self.pb_getAccountTransactionIds.setText(_translate("MainWindow", "getAccountTransactionIds", None))
        self.pb_getAccountPublicKey.setText(_translate("MainWindow", "getAccountPublicKey", None))
        self.pb_sendMoney.setText(_translate("MainWindow", "sendMoney", None))
        self.pb_getBalance.setText(_translate("MainWindow", "getBalance", None))
        self.pb_rsConvert.setText(_translate("MainWindow", "rsConvert", None))
        self.pb_setAccountInfo.setText(_translate("MainWindow", "setAccountInfo", None))
        self.pb_startForging.setText(_translate("MainWindow", "startForging", None))
        self.pb_getGuaranteedBalance.setText(_translate("MainWindow", "getGuaranteedBalance", None))
        self.pb_generateToken.setText(_translate("MainWindow", "generateToken", None))
        self.pb_getAliases.setText(_translate("MainWindow", "getAliases", None))
        self.pb_getAlias.setText(_translate("MainWindow", "getAlias", None))
        self.pb_buyAlias.setText(_translate("MainWindow", "buyAlias", None))
        self.pb_sellAlias.setText(_translate("MainWindow", "sellAlias", None))
        self.pb_setAlias.setText(_translate("MainWindow", "setAlias", None))
        self.tabWidget_querySel.setTabText(self.tabWidget_querySel.indexOf(self.tab_5), _translate("MainWindow", "Acct+MSGs", None))
        self.pb_getBidOrderIds.setText(_translate("MainWindow", "getBidOrderIds", None))
        self.pb_cancelAskOrder.setText(_translate("MainWindow", "cancelAskOrder", None))
        self.pb_cancelBidOrder.setText(_translate("MainWindow", "cancelBidOrder", None))
        self.pb_placeBidOrder.setText(_translate("MainWindow", "placeBidOrder", None))
        self.pb_getAskOrder.setText(_translate("MainWindow", "getAskOrder", None))
        self.pb_getAskOrderIds.setText(_translate("MainWindow", "getAskOrderIds", None))
        self.pb_getBidOrder.setText(_translate("MainWindow", "getBidOrder", None))
        self.pb_placeAskOrder.setText(_translate("MainWindow", "placeAskOrder", None))
        self.pb_getAccountCurrentBidOrderIds.setText(_translate("MainWindow", "getAccCurrBidOrderIds", None))
        self.pb_getAccountCurrentAskOrderIds.setText(_translate("MainWindow", "getAccCurrAskOrderIds", None))
        self.pb_transferAsset.setText(_translate("MainWindow", "transferAsset", None))
        self.pb_getTrades.setText(_translate("MainWindow", "getTrades", None))
        self.pb_getAssets.setText(_translate("MainWindow", "getAssets", None))
        self.pb_getAllOpenOrders.setText(_translate("MainWindow", "getAllOpenOrders", None))
        self.pb_getAllAssets.setText(_translate("MainWindow", "getAllAssets", None))
        self.pb_getAskOrders.setText(_translate("MainWindow", "getAskOrders", None))
        self.pb_getBidOrders.setText(_translate("MainWindow", "getBidOrders", None))
        self.pb_getAssetIds.setText(_translate("MainWindow", "getAssetIds", None))
        self.pb_getAssetsByIssuer.setText(_translate("MainWindow", "getAssetsByIssuer", None))
        self.pb_getAsset.setText(_translate("MainWindow", "getAsset", None))
        self.pb_issueAsset.setText(_translate("MainWindow", "issueAsset", None))
        self.pb_getAllTrades.setText(_translate("MainWindow", "getAllTrades", None))
        self.pb_dgsPriceChange.setText(_translate("MainWindow", "dgsPriceChange", None))
        self.pb_getDGSPurchase.setText(_translate("MainWindow", "getDGSPurchase", None))
        self.pb_dgsFeedback.setText(_translate("MainWindow", "dgsFeedback", None))
        self.pb_dgsQuantityChange.setText(_translate("MainWindow", "dgsQuantityChange", None))
        self.pb_getDGSPendingPurchases.setText(_translate("MainWindow", "getDGSPendingPurchases", None))
        self.pb_dgsDelisting.setText(_translate("MainWindow", "dgsDelisting", None))
        self.pb_dgsListing.setText(_translate("MainWindow", "dgsListing", None))
        self.pb_dgsPurchase.setText(_translate("MainWindow", "dgsPurchase", None))
        self.pb_dgsDelivery.setText(_translate("MainWindow", "dgsDelivery", None))
        self.pb_dgsRefund.setText(_translate("MainWindow", "dgsRefund", None))
        self.pb_getDGSGoods.setText(_translate("MainWindow", "getDGSGoods", None))
        self.pb_getDGSGood.setText(_translate("MainWindow", "getDGSGood", None))
        self.pb_getDGSPurchases.setText(_translate("MainWindow", "getDGSPurchases", None))
        self.tabWidget_querySel.setTabText(self.tabWidget_querySel.indexOf(self.tab_6), _translate("MainWindow", "AE+DGS", None))
        self.label_fullQuery.setText(_translate("MainWindow", "rawQuery", None))
        self.pb_sendQuery.setText(_translate("MainWindow", "send Query once", None))
        self.pb_clearText.setText(_translate("MainWindow", "clear", None))
        self.cb_scrollCheck.setText(_translate("MainWindow", "scroll", None))
        self.gb_poll7.setTitle(_translate("MainWindow", "Poll", None))
        self.actionMenu.setText(_translate("MainWindow", "menu", None))

from PyKDE4.kdeui import KLed
