# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nxtWin0_h900.ui'
#
# Created: Sat Jul  5 16:58:37 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1280, 880)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 880))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 880))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget_MainDetail = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_MainDetail.setGeometry(QtCore.QRect(550, -5, 731, 880))
        self.tabWidget_MainDetail.setObjectName(_fromUtf8("tabWidget_MainDetail"))
        self.tab_state = QtGui.QWidget()
        self.tab_state.setObjectName(_fromUtf8("tab_state"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.tab_state)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 661, 781))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_state = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_state.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_state.setMargin(2)
        self.gridLayout_state.setObjectName(_fromUtf8("gridLayout_state"))
        self.label_state_numPollsD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numPollsD.setFont(font)
        self.label_state_numPollsD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numPollsD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numPollsD.setObjectName(_fromUtf8("label_state_numPollsD"))
        self.gridLayout_state.addWidget(self.label_state_numPollsD, 19, 2, 1, 1)
        self.label_state_numberOfAccounts = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfAccounts.setFont(font)
        self.label_state_numberOfAccounts.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfAccounts.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfAccounts.setObjectName(_fromUtf8("label_state_numberOfAccounts"))
        self.gridLayout_state.addWidget(self.label_state_numberOfAccounts, 8, 0, 1, 1)
        self.label_state_numVotes = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numVotes.setFont(font)
        self.label_state_numVotes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numVotes.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numVotes.setObjectName(_fromUtf8("label_state_numVotes"))
        self.gridLayout_state.addWidget(self.label_state_numVotes, 20, 0, 1, 1)
        self.label_state_numberOfAliasesD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfAliasesD.setFont(font)
        self.label_state_numberOfAliasesD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfAliasesD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfAliasesD.setObjectName(_fromUtf8("label_state_numberOfAliasesD"))
        self.gridLayout_state.addWidget(self.label_state_numberOfAliasesD, 18, 2, 1, 1)
        self.label_state_numTrades = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numTrades.setFont(font)
        self.label_state_numTrades.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numTrades.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numTrades.setObjectName(_fromUtf8("label_state_numTrades"))
        self.gridLayout_state.addWidget(self.label_state_numTrades, 6, 0, 1, 1)
        self.label_state_numUnlAccs = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numUnlAccs.setFont(font)
        self.label_state_numUnlAccs.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numUnlAccs.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numUnlAccs.setObjectName(_fromUtf8("label_state_numUnlAccs"))
        self.gridLayout_state.addWidget(self.label_state_numUnlAccs, 7, 0, 1, 1)
        self.label_state_numTradesD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numTradesD.setFont(font)
        self.label_state_numTradesD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numTradesD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numTradesD.setObjectName(_fromUtf8("label_state_numTradesD"))
        self.gridLayout_state.addWidget(self.label_state_numTradesD, 6, 2, 1, 1)
        self.label_state_lastBlockchainFeeder = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_lastBlockchainFeeder.setFont(font)
        self.label_state_lastBlockchainFeeder.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_lastBlockchainFeeder.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_lastBlockchainFeeder.setObjectName(_fromUtf8("label_state_lastBlockchainFeeder"))
        self.gridLayout_state.addWidget(self.label_state_lastBlockchainFeeder, 11, 0, 1, 1)
        self.label_state_time = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_time.setFont(font)
        self.label_state_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_time.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_time.setObjectName(_fromUtf8("label_state_time"))
        self.gridLayout_state.addWidget(self.label_state_time, 0, 0, 1, 1)
        self.label_state_numberOfAssets = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfAssets.setFont(font)
        self.label_state_numberOfAssets.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfAssets.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfAssets.setObjectName(_fromUtf8("label_state_numberOfAssets"))
        self.gridLayout_state.addWidget(self.label_state_numberOfAssets, 5, 0, 1, 1)
        self.label_state_totalMemory = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_totalMemory.setFont(font)
        self.label_state_totalMemory.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_totalMemory.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_totalMemory.setObjectName(_fromUtf8("label_state_totalMemory"))
        self.gridLayout_state.addWidget(self.label_state_totalMemory, 14, 0, 1, 1)
        self.label_state_numberOfTransactions = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfTransactions.setFont(font)
        self.label_state_numberOfTransactions.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfTransactions.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfTransactions.setObjectName(_fromUtf8("label_state_numberOfTransactions"))
        self.gridLayout_state.addWidget(self.label_state_numberOfTransactions, 3, 0, 1, 1)
        self.label_state_numberOfPeersD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfPeersD.setFont(font)
        self.label_state_numberOfPeersD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfPeersD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfPeersD.setObjectName(_fromUtf8("label_state_numberOfPeersD"))
        self.gridLayout_state.addWidget(self.label_state_numberOfPeersD, 10, 2, 1, 1)
        self.label_state_numberOfPeers = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfPeers.setFont(font)
        self.label_state_numberOfPeers.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfPeers.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfPeers.setObjectName(_fromUtf8("label_state_numberOfPeers"))
        self.gridLayout_state.addWidget(self.label_state_numberOfPeers, 10, 0, 1, 1)
        self.label_state_lastBlock = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_lastBlock.setFont(font)
        self.label_state_lastBlock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_lastBlock.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_lastBlock.setObjectName(_fromUtf8("label_state_lastBlock"))
        self.gridLayout_state.addWidget(self.label_state_lastBlock, 1, 0, 1, 1)
        self.label_proc = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_proc.setFont(font)
        self.label_proc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_proc.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_proc.setObjectName(_fromUtf8("label_proc"))
        self.gridLayout_state.addWidget(self.label_proc, 13, 0, 1, 1)
        self.label_state_cumulDiff = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_cumulDiff.setFont(font)
        self.label_state_cumulDiff.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_cumulDiff.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_cumulDiff.setObjectName(_fromUtf8("label_state_cumulDiff"))
        self.gridLayout_state.addWidget(self.label_state_cumulDiff, 9, 0, 1, 1)
        self.label_state_numberOfOrdersD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfOrdersD.setFont(font)
        self.label_state_numberOfOrdersD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfOrdersD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfOrdersD.setObjectName(_fromUtf8("label_state_numberOfOrdersD"))
        self.gridLayout_state.addWidget(self.label_state_numberOfOrdersD, 4, 2, 1, 1)
        self.label_state_version = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_version.setFont(font)
        self.label_state_version.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_version.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_version.setObjectName(_fromUtf8("label_state_version"))
        self.gridLayout_state.addWidget(self.label_state_version, 17, 0, 1, 1)
        self.label_state_numberOfOrders = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfOrders.setFont(font)
        self.label_state_numberOfOrders.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfOrders.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfOrders.setObjectName(_fromUtf8("label_state_numberOfOrders"))
        self.gridLayout_state.addWidget(self.label_state_numberOfOrders, 4, 0, 1, 1)
        self.label_state_totalEffectiveBalance = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_totalEffectiveBalance.setFont(font)
        self.label_state_totalEffectiveBalance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_totalEffectiveBalance.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_totalEffectiveBalance.setObjectName(_fromUtf8("label_state_totalEffectiveBalance"))
        self.gridLayout_state.addWidget(self.label_state_totalEffectiveBalance, 12, 0, 1, 1)
        self.label_state_numberOfBlocks = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_state_numberOfBlocks.sizePolicy().hasHeightForWidth())
        self.label_state_numberOfBlocks.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfBlocks.setFont(font)
        self.label_state_numberOfBlocks.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfBlocks.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfBlocks.setObjectName(_fromUtf8("label_state_numberOfBlocks"))
        self.gridLayout_state.addWidget(self.label_state_numberOfBlocks, 2, 0, 1, 1)
        self.label_state_freeMemory = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_freeMemory.setFont(font)
        self.label_state_freeMemory.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_freeMemory.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_freeMemory.setObjectName(_fromUtf8("label_state_freeMemory"))
        self.gridLayout_state.addWidget(self.label_state_freeMemory, 15, 0, 1, 1)
        self.label_state_cumulDiffD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_cumulDiffD.setFont(font)
        self.label_state_cumulDiffD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_cumulDiffD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_cumulDiffD.setObjectName(_fromUtf8("label_state_cumulDiffD"))
        self.gridLayout_state.addWidget(self.label_state_cumulDiffD, 9, 2, 1, 1)
        self.label_state_lastBlockchainFeederD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_lastBlockchainFeederD.setFont(font)
        self.label_state_lastBlockchainFeederD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_lastBlockchainFeederD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_lastBlockchainFeederD.setObjectName(_fromUtf8("label_state_lastBlockchainFeederD"))
        self.gridLayout_state.addWidget(self.label_state_lastBlockchainFeederD, 11, 2, 1, 1)
        self.label_state_numberOfAssetsD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfAssetsD.setFont(font)
        self.label_state_numberOfAssetsD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfAssetsD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfAssetsD.setObjectName(_fromUtf8("label_state_numberOfAssetsD"))
        self.gridLayout_state.addWidget(self.label_state_numberOfAssetsD, 5, 2, 1, 1)
        self.label_state_totalEffectiveBalanceD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_totalEffectiveBalanceD.setFont(font)
        self.label_state_totalEffectiveBalanceD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_totalEffectiveBalanceD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_totalEffectiveBalanceD.setObjectName(_fromUtf8("label_state_totalEffectiveBalanceD"))
        self.gridLayout_state.addWidget(self.label_state_totalEffectiveBalanceD, 12, 2, 1, 1)
        self.label_state_availableProcessorsD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_availableProcessorsD.setFont(font)
        self.label_state_availableProcessorsD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_availableProcessorsD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_availableProcessorsD.setObjectName(_fromUtf8("label_state_availableProcessorsD"))
        self.gridLayout_state.addWidget(self.label_state_availableProcessorsD, 13, 2, 1, 1)
        self.label_state_totalMemoryD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_totalMemoryD.setFont(font)
        self.label_state_totalMemoryD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_totalMemoryD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_totalMemoryD.setObjectName(_fromUtf8("label_state_totalMemoryD"))
        self.gridLayout_state.addWidget(self.label_state_totalMemoryD, 14, 2, 1, 1)
        self.label_state_freeMemoryD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_freeMemoryD.setFont(font)
        self.label_state_freeMemoryD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_freeMemoryD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_freeMemoryD.setObjectName(_fromUtf8("label_state_freeMemoryD"))
        self.gridLayout_state.addWidget(self.label_state_freeMemoryD, 15, 2, 1, 1)
        self.label_state_maxMemoryD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_maxMemoryD.setFont(font)
        self.label_state_maxMemoryD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_maxMemoryD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_maxMemoryD.setObjectName(_fromUtf8("label_state_maxMemoryD"))
        self.gridLayout_state.addWidget(self.label_state_maxMemoryD, 16, 2, 1, 1)
        self.label_state_versionD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_versionD.setFont(font)
        self.label_state_versionD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_versionD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_versionD.setObjectName(_fromUtf8("label_state_versionD"))
        self.gridLayout_state.addWidget(self.label_state_versionD, 17, 2, 1, 1)
        self.label_state_numberOfTransactionsD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfTransactionsD.setFont(font)
        self.label_state_numberOfTransactionsD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfTransactionsD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfTransactionsD.setObjectName(_fromUtf8("label_state_numberOfTransactionsD"))
        self.gridLayout_state.addWidget(self.label_state_numberOfTransactionsD, 3, 2, 1, 1)
        self.label_state_numberOfBlocksD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfBlocksD.setFont(font)
        self.label_state_numberOfBlocksD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfBlocksD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfBlocksD.setObjectName(_fromUtf8("label_state_numberOfBlocksD"))
        self.gridLayout_state.addWidget(self.label_state_numberOfBlocksD, 2, 2, 1, 1)
        self.label_state_lastBlockD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_lastBlockD.setFont(font)
        self.label_state_lastBlockD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_lastBlockD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_lastBlockD.setObjectName(_fromUtf8("label_state_lastBlockD"))
        self.gridLayout_state.addWidget(self.label_state_lastBlockD, 1, 2, 1, 1)
        self.label_state_timeD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_timeD.setFont(font)
        self.label_state_timeD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_timeD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_timeD.setObjectName(_fromUtf8("label_state_timeD"))
        self.gridLayout_state.addWidget(self.label_state_timeD, 0, 2, 1, 1)
        self.label_state_maxMemory = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_maxMemory.setFont(font)
        self.label_state_maxMemory.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_maxMemory.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_maxMemory.setObjectName(_fromUtf8("label_state_maxMemory"))
        self.gridLayout_state.addWidget(self.label_state_maxMemory, 16, 0, 1, 1)
        self.label_state_numUnlAccsD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numUnlAccsD.setFont(font)
        self.label_state_numUnlAccsD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numUnlAccsD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numUnlAccsD.setObjectName(_fromUtf8("label_state_numUnlAccsD"))
        self.gridLayout_state.addWidget(self.label_state_numUnlAccsD, 7, 2, 1, 1)
        self.label_state_numberOfAccountsD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfAccountsD.setFont(font)
        self.label_state_numberOfAccountsD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfAccountsD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfAccountsD.setObjectName(_fromUtf8("label_state_numberOfAccountsD"))
        self.gridLayout_state.addWidget(self.label_state_numberOfAccountsD, 8, 2, 1, 1)
        self.label_state_numVotesD = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numVotesD.setFont(font)
        self.label_state_numVotesD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numVotesD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numVotesD.setObjectName(_fromUtf8("label_state_numVotesD"))
        self.gridLayout_state.addWidget(self.label_state_numVotesD, 20, 2, 1, 1)
        self.label_state_numPolls = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numPolls.setFont(font)
        self.label_state_numPolls.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numPolls.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numPolls.setObjectName(_fromUtf8("label_state_numPolls"))
        self.gridLayout_state.addWidget(self.label_state_numPolls, 19, 0, 1, 1)
        self.label_state_numberOfAliases = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_numberOfAliases.setFont(font)
        self.label_state_numberOfAliases.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_numberOfAliases.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_state_numberOfAliases.setObjectName(_fromUtf8("label_state_numberOfAliases"))
        self.gridLayout_state.addWidget(self.label_state_numberOfAliases, 18, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_state.addItem(spacerItem, 4, 1, 1, 1)
        self.tabWidget_MainDetail.addTab(self.tab_state, _fromUtf8(""))
        self.tab_block = QtGui.QWidget()
        self.tab_block.setObjectName(_fromUtf8("tab_block"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tab_block)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 10, 701, 821))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_block = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_block.setSpacing(0)
        self.gridLayout_block.setMargin(0)
        self.gridLayout_block.setObjectName(_fromUtf8("gridLayout_block"))
        self.label_block_payloadLength = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_payloadLength.setFont(font)
        self.label_block_payloadLength.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_payloadLength.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_payloadLength.setObjectName(_fromUtf8("label_block_payloadLength"))
        self.gridLayout_block.addWidget(self.label_block_payloadLength, 3, 0, 1, 1)
        self.label_block_payloadLengthD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_payloadLengthD.setFont(font)
        self.label_block_payloadLengthD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_payloadLengthD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_payloadLengthD.setObjectName(_fromUtf8("label_block_payloadLengthD"))
        self.gridLayout_block.addWidget(self.label_block_payloadLengthD, 3, 2, 1, 1)
        self.plainTextEdit_blockSigD = QtGui.QPlainTextEdit(self.gridLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_blockSigD.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_blockSigD.setSizePolicy(sizePolicy)
        self.plainTextEdit_blockSigD.setMinimumSize(QtCore.QSize(500, 0))
        self.plainTextEdit_blockSigD.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit_blockSigD.setFont(font)
        self.plainTextEdit_blockSigD.setFrameShape(QtGui.QFrame.Panel)
        self.plainTextEdit_blockSigD.setFrameShadow(QtGui.QFrame.Raised)
        self.plainTextEdit_blockSigD.setDocumentTitle(_fromUtf8(""))
        self.plainTextEdit_blockSigD.setUndoRedoEnabled(False)
        self.plainTextEdit_blockSigD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit_blockSigD.setObjectName(_fromUtf8("plainTextEdit_blockSigD"))
        self.gridLayout_block.addWidget(self.plainTextEdit_blockSigD, 11, 2, 1, 1)
        self.label_block_timeD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_timeD.setFont(font)
        self.label_block_timeD.setTextFormat(QtCore.Qt.PlainText)
        self.label_block_timeD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_timeD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_timeD.setObjectName(_fromUtf8("label_block_timeD"))
        self.gridLayout_block.addWidget(self.label_block_timeD, 1, 2, 1, 1)
        self.label_block_numberOfTransactions = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_numberOfTransactions.setFont(font)
        self.label_block_numberOfTransactions.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_numberOfTransactions.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_numberOfTransactions.setObjectName(_fromUtf8("label_block_numberOfTransactions"))
        self.gridLayout_block.addWidget(self.label_block_numberOfTransactions, 14, 0, 1, 1)
        self.label_block_transactions = QtGui.QLabel(self.gridLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_block_transactions.sizePolicy().hasHeightForWidth())
        self.label_block_transactions.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_transactions.setFont(font)
        self.label_block_transactions.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_transactions.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_transactions.setObjectName(_fromUtf8("label_block_transactions"))
        self.gridLayout_block.addWidget(self.label_block_transactions, 15, 0, 1, 1)
        self.label_block_previousBlockHash = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_previousBlockHash.setFont(font)
        self.label_block_previousBlockHash.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_previousBlockHash.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_previousBlockHash.setObjectName(_fromUtf8("label_block_previousBlockHash"))
        self.gridLayout_block.addWidget(self.label_block_previousBlockHash, 12, 0, 1, 1)
        self.label_block_nextBlockD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_nextBlockD.setFont(font)
        self.label_block_nextBlockD.setTextFormat(QtCore.Qt.PlainText)
        self.label_block_nextBlockD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_nextBlockD.setWordWrap(True)
        self.label_block_nextBlockD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_nextBlockD.setObjectName(_fromUtf8("label_block_nextBlockD"))
        self.gridLayout_block.addWidget(self.label_block_nextBlockD, 4, 2, 1, 1)
        self.label_block_prevBlock = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_prevBlock.setFont(font)
        self.label_block_prevBlock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_prevBlock.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_prevBlock.setObjectName(_fromUtf8("label_block_prevBlock"))
        self.gridLayout_block.addWidget(self.label_block_prevBlock, 5, 0, 1, 1)
        self.label_block_addressD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_addressD.setFont(font)
        self.label_block_addressD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_addressD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_addressD.setObjectName(_fromUtf8("label_block_addressD"))
        self.gridLayout_block.addWidget(self.label_block_addressD, 0, 2, 1, 1)
        self.label_block_baseTargetD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_baseTargetD.setFont(font)
        self.label_block_baseTargetD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_baseTargetD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_baseTargetD.setObjectName(_fromUtf8("label_block_baseTargetD"))
        self.gridLayout_block.addWidget(self.label_block_baseTargetD, 7, 2, 1, 1)
        self.label_block_previousBlockHashD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_block_previousBlockHashD.setFont(font)
        self.label_block_previousBlockHashD.setTextFormat(QtCore.Qt.PlainText)
        self.label_block_previousBlockHashD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_previousBlockHashD.setWordWrap(True)
        self.label_block_previousBlockHashD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_previousBlockHashD.setObjectName(_fromUtf8("label_block_previousBlockHashD"))
        self.gridLayout_block.addWidget(self.label_block_previousBlockHashD, 12, 2, 1, 1)
        self.label_block_paylHash = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_paylHash.setFont(font)
        self.label_block_paylHash.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_paylHash.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_paylHash.setObjectName(_fromUtf8("label_block_paylHash"))
        self.gridLayout_block.addWidget(self.label_block_paylHash, 6, 0, 1, 1)
        self.label_block_paylHashD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_block_paylHashD.setFont(font)
        self.label_block_paylHashD.setTextFormat(QtCore.Qt.PlainText)
        self.label_block_paylHashD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_paylHashD.setWordWrap(True)
        self.label_block_paylHashD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_paylHashD.setObjectName(_fromUtf8("label_block_paylHashD"))
        self.gridLayout_block.addWidget(self.label_block_paylHashD, 6, 2, 1, 1)
        self.label_block_height = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_height.setFont(font)
        self.label_block_height.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_height.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_height.setObjectName(_fromUtf8("label_block_height"))
        self.gridLayout_block.addWidget(self.label_block_height, 8, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_block.addItem(spacerItem1, 4, 1, 1, 1)
        self.label_block_version = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_version.setFont(font)
        self.label_block_version.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_version.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_version.setObjectName(_fromUtf8("label_block_version"))
        self.gridLayout_block.addWidget(self.label_block_version, 16, 0, 1, 1)
        self.label_block_versionD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_versionD.setFont(font)
        self.label_block_versionD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_versionD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_versionD.setObjectName(_fromUtf8("label_block_versionD"))
        self.gridLayout_block.addWidget(self.label_block_versionD, 16, 2, 1, 1)
        self.label_block_nextBlock = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_nextBlock.setFont(font)
        self.label_block_nextBlock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_nextBlock.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_nextBlock.setObjectName(_fromUtf8("label_block_nextBlock"))
        self.gridLayout_block.addWidget(self.label_block_nextBlock, 4, 0, 1, 1)
        self.label_block_generationSignatureD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_block_generationSignatureD.setFont(font)
        self.label_block_generationSignatureD.setTextFormat(QtCore.Qt.PlainText)
        self.label_block_generationSignatureD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_generationSignatureD.setWordWrap(True)
        self.label_block_generationSignatureD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_generationSignatureD.setObjectName(_fromUtf8("label_block_generationSignatureD"))
        self.gridLayout_block.addWidget(self.label_block_generationSignatureD, 10, 2, 1, 1)
        self.label_block_totalFeeNQTD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_totalFeeNQTD.setFont(font)
        self.label_block_totalFeeNQTD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_totalFeeNQTD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_totalFeeNQTD.setObjectName(_fromUtf8("label_block_totalFeeNQTD"))
        self.gridLayout_block.addWidget(self.label_block_totalFeeNQTD, 13, 2, 1, 1)
        self.label_block_heightD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_heightD.setFont(font)
        self.label_block_heightD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_heightD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_heightD.setObjectName(_fromUtf8("label_block_heightD"))
        self.gridLayout_block.addWidget(self.label_block_heightD, 8, 2, 1, 1)
        self.label_block_generatorD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_generatorD.setFont(font)
        self.label_block_generatorD.setTextFormat(QtCore.Qt.PlainText)
        self.label_block_generatorD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_generatorD.setWordWrap(True)
        self.label_block_generatorD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_generatorD.setObjectName(_fromUtf8("label_block_generatorD"))
        self.gridLayout_block.addWidget(self.label_block_generatorD, 2, 2, 1, 1)
        self.label_block_totalFeeNQT = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_totalFeeNQT.setFont(font)
        self.label_block_totalFeeNQT.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_totalFeeNQT.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_totalFeeNQT.setObjectName(_fromUtf8("label_block_totalFeeNQT"))
        self.gridLayout_block.addWidget(self.label_block_totalFeeNQT, 13, 0, 1, 1)
        self.label_block_baseTarget = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_baseTarget.setFont(font)
        self.label_block_baseTarget.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_baseTarget.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_baseTarget.setObjectName(_fromUtf8("label_block_baseTarget"))
        self.gridLayout_block.addWidget(self.label_block_baseTarget, 7, 0, 1, 1)
        self.label_block_generationSignature = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_generationSignature.setFont(font)
        self.label_block_generationSignature.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_generationSignature.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_generationSignature.setObjectName(_fromUtf8("label_block_generationSignature"))
        self.gridLayout_block.addWidget(self.label_block_generationSignature, 10, 0, 1, 1)
        self.label_block_numberOfTransactionsD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_numberOfTransactionsD.setFont(font)
        self.label_block_numberOfTransactionsD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_numberOfTransactionsD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_numberOfTransactionsD.setObjectName(_fromUtf8("label_block_numberOfTransactionsD"))
        self.gridLayout_block.addWidget(self.label_block_numberOfTransactionsD, 14, 2, 1, 1)
        self.label_block_generator = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_generator.setFont(font)
        self.label_block_generator.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_generator.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_generator.setObjectName(_fromUtf8("label_block_generator"))
        self.gridLayout_block.addWidget(self.label_block_generator, 2, 0, 1, 1)
        self.label_block_prevBlockD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_prevBlockD.setFont(font)
        self.label_block_prevBlockD.setTextFormat(QtCore.Qt.PlainText)
        self.label_block_prevBlockD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_prevBlockD.setWordWrap(True)
        self.label_block_prevBlockD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_prevBlockD.setObjectName(_fromUtf8("label_block_prevBlockD"))
        self.gridLayout_block.addWidget(self.label_block_prevBlockD, 5, 2, 1, 1)
        self.plainTextEdit_TXsD = QtGui.QPlainTextEdit(self.gridLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_TXsD.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_TXsD.setSizePolicy(sizePolicy)
        self.plainTextEdit_TXsD.setMinimumSize(QtCore.QSize(500, 0))
        self.plainTextEdit_TXsD.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit_TXsD.setFont(font)
        self.plainTextEdit_TXsD.setFrameShape(QtGui.QFrame.Panel)
        self.plainTextEdit_TXsD.setFrameShadow(QtGui.QFrame.Raised)
        self.plainTextEdit_TXsD.setDocumentTitle(_fromUtf8(""))
        self.plainTextEdit_TXsD.setUndoRedoEnabled(False)
        self.plainTextEdit_TXsD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit_TXsD.setObjectName(_fromUtf8("plainTextEdit_TXsD"))
        self.gridLayout_block.addWidget(self.plainTextEdit_TXsD, 15, 2, 1, 1)
        self.label_block_address = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_address.setFont(font)
        self.label_block_address.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_address.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_address.setObjectName(_fromUtf8("label_block_address"))
        self.gridLayout_block.addWidget(self.label_block_address, 0, 0, 1, 1)
        self.label_block_timestamp = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_timestamp.setFont(font)
        self.label_block_timestamp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_timestamp.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_timestamp.setObjectName(_fromUtf8("label_block_timestamp"))
        self.gridLayout_block.addWidget(self.label_block_timestamp, 1, 0, 1, 1)
        self.label_block_blockSignature = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_blockSignature.setFont(font)
        self.label_block_blockSignature.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_blockSignature.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_blockSignature.setObjectName(_fromUtf8("label_block_blockSignature"))
        self.gridLayout_block.addWidget(self.label_block_blockSignature, 11, 0, 1, 1)
        self.label_block_totAmountNQT = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_totAmountNQT.setFont(font)
        self.label_block_totAmountNQT.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_totAmountNQT.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_totAmountNQT.setObjectName(_fromUtf8("label_block_totAmountNQT"))
        self.gridLayout_block.addWidget(self.label_block_totAmountNQT, 9, 0, 1, 1)
        self.label_block_totalAmountNQTD = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_block_totalAmountNQTD.setFont(font)
        self.label_block_totalAmountNQTD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_totalAmountNQTD.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_block_totalAmountNQTD.setObjectName(_fromUtf8("label_block_totalAmountNQTD"))
        self.gridLayout_block.addWidget(self.label_block_totalAmountNQTD, 9, 2, 1, 1)
        self.tabWidget_MainDetail.addTab(self.tab_block, _fromUtf8(""))
        self.tab_TXs = QtGui.QWidget()
        self.tab_TXs.setObjectName(_fromUtf8("tab_TXs"))
        self.tw_newTXs = QtGui.QTableWidget(self.tab_TXs)
        self.tw_newTXs.setGeometry(QtCore.QRect(20, 650, 671, 171))
        self.tw_newTXs.setObjectName(_fromUtf8("tw_newTXs"))
        self.tw_newTXs.setColumnCount(0)
        self.tw_newTXs.setRowCount(0)
        self.pb_clearText_2 = QtGui.QPushButton(self.tab_TXs)
        self.pb_clearText_2.setGeometry(QtCore.QRect(625, 10, 81, 51))
        self.pb_clearText_2.setObjectName(_fromUtf8("pb_clearText_2"))
        self.textEdit_newTXs = QtGui.QTextEdit(self.tab_TXs)
        self.textEdit_newTXs.setGeometry(QtCore.QRect(20, 10, 591, 621))
        self.textEdit_newTXs.setObjectName(_fromUtf8("textEdit_newTXs"))
        self.tabWidget_MainDetail.addTab(self.tab_TXs, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_7)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(370, 675, 346, 161))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit_leaseRec = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_leaseRec.setObjectName(_fromUtf8("lineEdit_leaseRec"))
        self.gridLayout_2.addWidget(self.lineEdit_leaseRec, 0, 1, 1, 1)
        self.pb_lease = QtGui.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_lease.setFont(font)
        self.pb_lease.setObjectName(_fromUtf8("pb_lease"))
        self.gridLayout_2.addWidget(self.pb_lease, 2, 0, 1, 1)
        self.lineEdit_leasePer = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_leasePer.setObjectName(_fromUtf8("lineEdit_leasePer"))
        self.gridLayout_2.addWidget(self.lineEdit_leasePer, 1, 1, 1, 1)
        self.label_leaseRec = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_leaseRec.setFont(font)
        self.label_leaseRec.setObjectName(_fromUtf8("label_leaseRec"))
        self.gridLayout_2.addWidget(self.label_leaseRec, 0, 0, 1, 1)
        self.label_leasePer = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_leasePer.setFont(font)
        self.label_leasePer.setObjectName(_fromUtf8("label_leasePer"))
        self.gridLayout_2.addWidget(self.label_leasePer, 1, 0, 1, 1)
        self.label_deadline_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_deadline_2.setFont(font)
        self.label_deadline_2.setObjectName(_fromUtf8("label_deadline_2"))
        self.gridLayout_2.addWidget(self.label_deadline_2, 3, 0, 1, 1)
        self.lineEdit_leaseDeadline = QtGui.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_leaseDeadline.setFont(font)
        self.lineEdit_leaseDeadline.setObjectName(_fromUtf8("lineEdit_leaseDeadline"))
        self.gridLayout_2.addWidget(self.lineEdit_leaseDeadline, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 2, 1, 1, 1)
        self.gb_ForgeCtrl = QtGui.QGroupBox(self.tab_7)
        self.gb_ForgeCtrl.setGeometry(QtCore.QRect(10, 720, 166, 116))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gb_ForgeCtrl.setFont(font)
        self.gb_ForgeCtrl.setFlat(False)
        self.gb_ForgeCtrl.setCheckable(True)
        self.gb_ForgeCtrl.setChecked(True)
        self.gb_ForgeCtrl.setObjectName(_fromUtf8("gb_ForgeCtrl"))
        self.lcdNumber_accBalEff = QtGui.QLCDNumber(self.gb_ForgeCtrl)
        self.lcdNumber_accBalEff.setGeometry(QtCore.QRect(45, 80, 121, 30))
        self.lcdNumber_accBalEff.setObjectName(_fromUtf8("lcdNumber_accBalEff"))
        self.label_balanceEff = QtGui.QLabel(self.gb_ForgeCtrl)
        self.label_balanceEff.setGeometry(QtCore.QRect(-5, 80, 51, 36))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_balanceEff.setFont(font)
        self.label_balanceEff.setAlignment(QtCore.Qt.AlignCenter)
        self.label_balanceEff.setObjectName(_fromUtf8("label_balanceEff"))
        self.lineEdit_remaining = QtGui.QLineEdit(self.gb_ForgeCtrl)
        self.lineEdit_remaining.setGeometry(QtCore.QRect(75, 55, 86, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_remaining.setFont(font)
        self.lineEdit_remaining.setObjectName(_fromUtf8("lineEdit_remaining"))
        self.lineEdit_ForgeDeadline = QtGui.QLineEdit(self.gb_ForgeCtrl)
        self.lineEdit_ForgeDeadline.setGeometry(QtCore.QRect(75, 30, 86, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_ForgeDeadline.setFont(font)
        self.lineEdit_ForgeDeadline.setObjectName(_fromUtf8("lineEdit_ForgeDeadline"))
        self.label_remaining = QtGui.QLabel(self.gb_ForgeCtrl)
        self.label_remaining.setGeometry(QtCore.QRect(0, 30, 70, 17))
        self.label_remaining.setObjectName(_fromUtf8("label_remaining"))
        self.label_Fdeadline = QtGui.QLabel(self.gb_ForgeCtrl)
        self.label_Fdeadline.setGeometry(QtCore.QRect(0, 55, 70, 17))
        self.label_Fdeadline.setObjectName(_fromUtf8("label_Fdeadline"))
        self.tabWidget_MainDetail.addTab(self.tab_7, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget_MainDetail.addTab(self.tab_4, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.textEdit_response = QtGui.QTextEdit(self.tab_6)
        self.textEdit_response.setGeometry(QtCore.QRect(10, 175, 711, 286))
        self.textEdit_response.setObjectName(_fromUtf8("textEdit_response"))
        self.pb_clearTextEditMSG = QtGui.QPushButton(self.tab_6)
        self.pb_clearTextEditMSG.setGeometry(QtCore.QRect(650, 150, 71, 21))
        self.pb_clearTextEditMSG.setObjectName(_fromUtf8("pb_clearTextEditMSG"))
        self.pb_test1 = QtGui.QPushButton(self.tab_6)
        self.pb_test1.setGeometry(QtCore.QRect(140, 15, 106, 41))
        self.pb_test1.setObjectName(_fromUtf8("pb_test1"))
        self.pb_test2 = QtGui.QPushButton(self.tab_6)
        self.pb_test2.setGeometry(QtCore.QRect(270, 15, 106, 41))
        self.pb_test2.setObjectName(_fromUtf8("pb_test2"))
        self.pb_test3 = QtGui.QPushButton(self.tab_6)
        self.pb_test3.setGeometry(QtCore.QRect(405, 15, 106, 41))
        self.pb_test3.setObjectName(_fromUtf8("pb_test3"))
        self.lineEdit_T1 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_T1.setGeometry(QtCore.QRect(95, 70, 266, 27))
        self.lineEdit_T1.setObjectName(_fromUtf8("lineEdit_T1"))
        self.label_1 = QtGui.QLabel(self.tab_6)
        self.label_1.setGeometry(QtCore.QRect(5, 75, 86, 17))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.lineEdit_T2 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_T2.setGeometry(QtCore.QRect(95, 105, 266, 27))
        self.lineEdit_T2.setObjectName(_fromUtf8("lineEdit_T2"))
        self.label_2 = QtGui.QLabel(self.tab_6)
        self.label_2.setGeometry(QtCore.QRect(5, 110, 86, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.textEdit_response_2 = QtGui.QTextEdit(self.tab_6)
        self.textEdit_response_2.setGeometry(QtCore.QRect(10, 495, 711, 336))
        self.textEdit_response_2.setObjectName(_fromUtf8("textEdit_response_2"))
        self.pb_clearResponse_2 = QtGui.QPushButton(self.tab_6)
        self.pb_clearResponse_2.setGeometry(QtCore.QRect(645, 465, 76, 21))
        self.pb_clearResponse_2.setObjectName(_fromUtf8("pb_clearResponse_2"))
        self.tabWidget_MainDetail.addTab(self.tab_6, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gb_files = QtGui.QGroupBox(self.tab_8)
        self.gb_files.setGeometry(QtCore.QRect(20, 10, 386, 821))
        self.gb_files.setAutoFillBackground(True)
        self.gb_files.setFlat(False)
        self.gb_files.setCheckable(True)
        self.gb_files.setObjectName(_fromUtf8("gb_files"))
        self.lineEdit_logF = QtGui.QLineEdit(self.gb_files)
        self.lineEdit_logF.setGeometry(QtCore.QRect(35, 35, 161, 26))
        self.lineEdit_logF.setObjectName(_fromUtf8("lineEdit_logF"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_8)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(475, 705, 248, 136))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_nxtWin6 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_nxtWin6.setObjectName(_fromUtf8("pushButton_nxtWin6"))
        self.gridLayout.addWidget(self.pushButton_nxtWin6, 2, 0, 1, 1)
        self.pushButton_nxtWin7 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_nxtWin7.setObjectName(_fromUtf8("pushButton_nxtWin7"))
        self.gridLayout.addWidget(self.pushButton_nxtWin7, 2, 1, 1, 1)
        self.pushButton_TESTBUTTON = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_TESTBUTTON.setFont(font)
        self.pushButton_TESTBUTTON.setObjectName(_fromUtf8("pushButton_TESTBUTTON"))
        self.gridLayout.addWidget(self.pushButton_TESTBUTTON, 4, 1, 1, 1)
        self.pushButton_nxtWin5 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_nxtWin5.setObjectName(_fromUtf8("pushButton_nxtWin5"))
        self.gridLayout.addWidget(self.pushButton_nxtWin5, 3, 1, 1, 1)
        self.pushButton_nxtWin2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_nxtWin2.setObjectName(_fromUtf8("pushButton_nxtWin2"))
        self.gridLayout.addWidget(self.pushButton_nxtWin2, 1, 0, 1, 1)
        self.pushButton_nxtWin4 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_nxtWin4.setObjectName(_fromUtf8("pushButton_nxtWin4"))
        self.gridLayout.addWidget(self.pushButton_nxtWin4, 1, 1, 1, 1)
        self.pushButton_nxtWin1 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_nxtWin1.setObjectName(_fromUtf8("pushButton_nxtWin1"))
        self.gridLayout.addWidget(self.pushButton_nxtWin1, 3, 0, 1, 1)
        self.gb_poll0 = QtGui.QGroupBox(self.tab_8)
        self.gb_poll0.setGeometry(QtCore.QRect(570, 660, 146, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.gb_poll0.setFont(font)
        self.gb_poll0.setCheckable(True)
        self.gb_poll0.setObjectName(_fromUtf8("gb_poll0"))
        self.lineEdit_pollTimer0 = QtGui.QLineEdit(self.gb_poll0)
        self.lineEdit_pollTimer0.setGeometry(QtCore.QRect(55, 2, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_pollTimer0.setFont(font)
        self.lineEdit_pollTimer0.setMaxLength(200)
        self.lineEdit_pollTimer0.setObjectName(_fromUtf8("lineEdit_pollTimer0"))
        self.kled_poll0 = KLed(self.gb_poll0)
        self.kled_poll0.setGeometry(QtCore.QRect(120, 0, 21, 21))
        self.kled_poll0.setColor(QtGui.QColor(0, 10, 250))
        self.kled_poll0.setObjectName(_fromUtf8("kled_poll0"))
        self.gb_poll0_2 = QtGui.QGroupBox(self.tab_8)
        self.gb_poll0_2.setGeometry(QtCore.QRect(570, 630, 146, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.gb_poll0_2.setFont(font)
        self.gb_poll0_2.setCheckable(True)
        self.gb_poll0_2.setChecked(False)
        self.gb_poll0_2.setObjectName(_fromUtf8("gb_poll0_2"))
        self.lineEdit_pollTimer0_2 = QtGui.QLineEdit(self.gb_poll0_2)
        self.lineEdit_pollTimer0_2.setGeometry(QtCore.QRect(55, 2, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_pollTimer0_2.setFont(font)
        self.lineEdit_pollTimer0_2.setMaxLength(200)
        self.lineEdit_pollTimer0_2.setObjectName(_fromUtf8("lineEdit_pollTimer0_2"))
        self.kled_poll0_2 = KLed(self.gb_poll0_2)
        self.kled_poll0_2.setGeometry(QtCore.QRect(120, 0, 21, 21))
        self.kled_poll0_2.setColor(QtGui.QColor(0, 10, 250))
        self.kled_poll0_2.setObjectName(_fromUtf8("kled_poll0_2"))
        self.tabWidget_MainDetail.addTab(self.tab_8, _fromUtf8(""))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(95, 25, 351, 136))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_account = QtGui.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_account.setFont(font)
        self.label_account.setAlignment(QtCore.Qt.AlignCenter)
        self.label_account.setObjectName(_fromUtf8("label_account"))
        self.gridLayout_4.addWidget(self.label_account, 1, 0, 1, 1)
        self.lineEdit_nxtServer = QtGui.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_nxtServer.setFont(font)
        self.lineEdit_nxtServer.setMaxLength(200)
        self.lineEdit_nxtServer.setObjectName(_fromUtf8("lineEdit_nxtServer"))
        self.gridLayout_4.addWidget(self.lineEdit_nxtServer, 0, 2, 1, 1)
        self.kled_connActive = KLed(self.gridLayoutWidget_4)
        self.kled_connActive.setColor(QtGui.QColor(0, 10, 250))
        self.kled_connActive.setObjectName(_fromUtf8("kled_connActive"))
        self.gridLayout_4.addWidget(self.kled_connActive, 0, 1, 1, 1)
        self.cb_passPh = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.cb_passPh.setText(_fromUtf8(""))
        self.cb_passPh.setObjectName(_fromUtf8("cb_passPh"))
        self.gridLayout_4.addWidget(self.cb_passPh, 3, 3, 1, 1)
        self.cb_acct = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.cb_acct.setText(_fromUtf8(""))
        self.cb_acct.setObjectName(_fromUtf8("cb_acct"))
        self.gridLayout_4.addWidget(self.cb_acct, 1, 3, 1, 1)
        self.cb_pollNRS = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.cb_pollNRS.setText(_fromUtf8(""))
        self.cb_pollNRS.setObjectName(_fromUtf8("cb_pollNRS"))
        self.gridLayout_4.addWidget(self.cb_pollNRS, 0, 3, 1, 1)
        self.lineEdit_passPhr = QtGui.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_passPhr.setFont(font)
        self.lineEdit_passPhr.setMaxLength(200)
        self.lineEdit_passPhr.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_passPhr.setObjectName(_fromUtf8("lineEdit_passPhr"))
        self.gridLayout_4.addWidget(self.lineEdit_passPhr, 3, 2, 1, 1)
        self.lineEdit_account0 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_account0.setFont(font)
        self.lineEdit_account0.setMaxLength(200)
        self.lineEdit_account0.setObjectName(_fromUtf8("lineEdit_account0"))
        self.gridLayout_4.addWidget(self.lineEdit_account0, 1, 2, 1, 1)
        self.label_NXTServer = QtGui.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_NXTServer.setFont(font)
        self.label_NXTServer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NXTServer.setObjectName(_fromUtf8("label_NXTServer"))
        self.gridLayout_4.addWidget(self.label_NXTServer, 0, 0, 1, 1)
        self.label_passPhrase = QtGui.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_passPhrase.setFont(font)
        self.label_passPhrase.setAlignment(QtCore.Qt.AlignCenter)
        self.label_passPhrase.setObjectName(_fromUtf8("label_passPhrase"))
        self.gridLayout_4.addWidget(self.label_passPhrase, 3, 0, 1, 1)
        self.kled_acctUnlocked = KLed(self.gridLayoutWidget_4)
        self.kled_acctUnlocked.setColor(QtGui.QColor(0, 10, 250))
        self.kled_acctUnlocked.setObjectName(_fromUtf8("kled_acctUnlocked"))
        self.gridLayout_4.addWidget(self.kled_acctUnlocked, 3, 1, 1, 1)
        self.kled_acctExists = KLed(self.gridLayoutWidget_4)
        self.kled_acctExists.setColor(QtGui.QColor(0, 10, 250))
        self.kled_acctExists.setObjectName(_fromUtf8("kled_acctExists"))
        self.gridLayout_4.addWidget(self.kled_acctExists, 1, 1, 1, 1)
        self.label_accountName = QtGui.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_accountName.setFont(font)
        self.label_accountName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_accountName.setObjectName(_fromUtf8("label_accountName"))
        self.gridLayout_4.addWidget(self.label_accountName, 2, 0, 1, 1)
        self.lineEdit_account0Name = QtGui.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_account0Name.setFont(font)
        self.lineEdit_account0Name.setText(_fromUtf8(""))
        self.lineEdit_account0Name.setMaxLength(200)
        self.lineEdit_account0Name.setObjectName(_fromUtf8("lineEdit_account0Name"))
        self.gridLayout_4.addWidget(self.lineEdit_account0Name, 2, 2, 1, 1)
        self.cb_acctName = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.cb_acctName.setText(_fromUtf8(""))
        self.cb_acctName.setObjectName(_fromUtf8("cb_acctName"))
        self.gridLayout_4.addWidget(self.cb_acctName, 2, 3, 1, 1)
        self.kled_acctName = KLed(self.gridLayoutWidget_4)
        self.kled_acctName.setColor(QtGui.QColor(0, 10, 250))
        self.kled_acctName.setObjectName(_fromUtf8("kled_acctName"))
        self.gridLayout_4.addWidget(self.kled_acctName, 2, 1, 1, 1)
        self.lineEdit_publicKey = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_publicKey.setGeometry(QtCore.QRect(70, 200, 466, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_publicKey.setFont(font)
        self.lineEdit_publicKey.setMaxLength(2000)
        self.lineEdit_publicKey.setObjectName(_fromUtf8("lineEdit_publicKey"))
        self.label_pubKey = QtGui.QLabel(self.centralwidget)
        self.label_pubKey.setGeometry(QtCore.QRect(5, 195, 62, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_pubKey.setFont(font)
        self.label_pubKey.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pubKey.setObjectName(_fromUtf8("label_pubKey"))
        self.lineEdit_acctDescr = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_acctDescr.setGeometry(QtCore.QRect(70, 230, 466, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_acctDescr.setFont(font)
        self.lineEdit_acctDescr.setText(_fromUtf8(""))
        self.lineEdit_acctDescr.setMaxLength(2000)
        self.lineEdit_acctDescr.setObjectName(_fromUtf8("lineEdit_acctDescr"))
        self.label_acctDescr = QtGui.QLabel(self.centralwidget)
        self.label_acctDescr.setGeometry(QtCore.QRect(5, 225, 62, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_acctDescr.setFont(font)
        self.label_acctDescr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_acctDescr.setObjectName(_fromUtf8("label_acctDescr"))
        self.groupBox_Balances = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_Balances.setGeometry(QtCore.QRect(100, 300, 326, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_Balances.setFont(font)
        self.groupBox_Balances.setTitle(_fromUtf8(""))
        self.groupBox_Balances.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_Balances.setFlat(False)
        self.groupBox_Balances.setCheckable(False)
        self.groupBox_Balances.setObjectName(_fromUtf8("groupBox_Balances"))
        self.groupBox_Bal_2 = QtGui.QGroupBox(self.groupBox_Balances)
        self.groupBox_Bal_2.setGeometry(QtCore.QRect(0, 80, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_Bal_2.setFont(font)
        self.groupBox_Bal_2.setObjectName(_fromUtf8("groupBox_Bal_2"))
        self.lcdNumber_accBalUnconf = QtGui.QLCDNumber(self.groupBox_Bal_2)
        self.lcdNumber_accBalUnconf.setGeometry(QtCore.QRect(0, 15, 170, 40))
        self.lcdNumber_accBalUnconf.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_accBalUnconf.setFont(font)
        self.lcdNumber_accBalUnconf.setObjectName(_fromUtf8("lcdNumber_accBalUnconf"))
        self.lcdNumber_accBalUnconfNQT = QtGui.QLCDNumber(self.groupBox_Bal_2)
        self.lcdNumber_accBalUnconfNQT.setGeometry(QtCore.QRect(180, 25, 140, 30))
        self.lcdNumber_accBalUnconfNQT.setMinimumSize(QtCore.QSize(120, 30))
        self.lcdNumber_accBalUnconfNQT.setObjectName(_fromUtf8("lcdNumber_accBalUnconfNQT"))
        self.label_balanceUnconf_2 = QtGui.QLabel(self.groupBox_Bal_2)
        self.label_balanceUnconf_2.setGeometry(QtCore.QRect(170, 25, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_balanceUnconf_2.setFont(font)
        self.label_balanceUnconf_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_balanceUnconf_2.setObjectName(_fromUtf8("label_balanceUnconf_2"))
        self.groupBox_Bal = QtGui.QGroupBox(self.groupBox_Balances)
        self.groupBox_Bal.setGeometry(QtCore.QRect(0, 10, 331, 71))
        self.groupBox_Bal.setObjectName(_fromUtf8("groupBox_Bal"))
        self.lcdNumber_accBal = QtGui.QLCDNumber(self.groupBox_Bal)
        self.lcdNumber_accBal.setGeometry(QtCore.QRect(0, 20, 170, 40))
        self.lcdNumber_accBal.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_accBal.setFont(font)
        self.lcdNumber_accBal.setObjectName(_fromUtf8("lcdNumber_accBal"))
        self.lcdNumber_accBalNQT = QtGui.QLCDNumber(self.groupBox_Bal)
        self.lcdNumber_accBalNQT.setGeometry(QtCore.QRect(180, 30, 140, 30))
        self.lcdNumber_accBalNQT.setMinimumSize(QtCore.QSize(120, 30))
        self.lcdNumber_accBalNQT.setObjectName(_fromUtf8("lcdNumber_accBalNQT"))
        self.label_balanceUnconf = QtGui.QLabel(self.groupBox_Bal)
        self.label_balanceUnconf.setGeometry(QtCore.QRect(170, 30, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_balanceUnconf.setFont(font)
        self.label_balanceUnconf.setAlignment(QtCore.Qt.AlignCenter)
        self.label_balanceUnconf.setObjectName(_fromUtf8("label_balanceUnconf"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(25, 500, 501, 341))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(25, 150, 441, 181))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lineEdit_amountNQT = QtGui.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_amountNQT.setFont(font)
        self.lineEdit_amountNQT.setObjectName(_fromUtf8("lineEdit_amountNQT"))
        self.gridLayout_5.addWidget(self.lineEdit_amountNQT, 0, 5, 1, 1)
        self.pb_sendMoney = QtGui.QPushButton(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_sendMoney.setFont(font)
        self.pb_sendMoney.setObjectName(_fromUtf8("pb_sendMoney"))
        self.gridLayout_5.addWidget(self.pb_sendMoney, 1, 3, 1, 1)
        self.label_amount = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_amount.setFont(font)
        self.label_amount.setObjectName(_fromUtf8("label_amount"))
        self.gridLayout_5.addWidget(self.label_amount, 0, 0, 1, 1)
        self.label_fee = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_fee.setFont(font)
        self.label_fee.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fee.setObjectName(_fromUtf8("label_fee"))
        self.gridLayout_5.addWidget(self.label_fee, 2, 0, 1, 1)
        self.lineEdit_fee = QtGui.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_fee.setFont(font)
        self.lineEdit_fee.setObjectName(_fromUtf8("lineEdit_fee"))
        self.gridLayout_5.addWidget(self.lineEdit_fee, 2, 3, 1, 1)
        self.lineEdit_amount = QtGui.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_amount.setFont(font)
        self.lineEdit_amount.setText(_fromUtf8(""))
        self.lineEdit_amount.setObjectName(_fromUtf8("lineEdit_amount"))
        self.gridLayout_5.addWidget(self.lineEdit_amount, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        self.label_arrow = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_arrow.setFont(font)
        self.label_arrow.setObjectName(_fromUtf8("label_arrow"))
        self.gridLayout_5.addWidget(self.label_arrow, 1, 0, 1, 1)
        self.lineEdit_feeNQT = QtGui.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_feeNQT.setFont(font)
        self.lineEdit_feeNQT.setObjectName(_fromUtf8("lineEdit_feeNQT"))
        self.gridLayout_5.addWidget(self.lineEdit_feeNQT, 2, 5, 1, 1)
        self.lineEdit_deadline = QtGui.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_deadline.setFont(font)
        self.lineEdit_deadline.setObjectName(_fromUtf8("lineEdit_deadline"))
        self.gridLayout_5.addWidget(self.lineEdit_deadline, 1, 5, 1, 1)
        self.label_deadline = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_deadline.setFont(font)
        self.label_deadline.setObjectName(_fromUtf8("label_deadline"))
        self.gridLayout_5.addWidget(self.label_deadline, 1, 4, 1, 1)
        self.label_Nxt = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_Nxt.setFont(font)
        self.label_Nxt.setObjectName(_fromUtf8("label_Nxt"))
        self.gridLayout_5.addWidget(self.label_Nxt, 0, 2, 1, 1)
        self.label_Nxt_2 = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_Nxt_2.setFont(font)
        self.label_Nxt_2.setObjectName(_fromUtf8("label_Nxt_2"))
        self.gridLayout_5.addWidget(self.label_Nxt_2, 2, 2, 1, 1)
        self.label_Nqt = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_Nqt.setFont(font)
        self.label_Nqt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Nqt.setObjectName(_fromUtf8("label_Nqt"))
        self.gridLayout_5.addWidget(self.label_Nqt, 0, 4, 1, 1)
        self.label_Nqt_2 = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_Nqt_2.setFont(font)
        self.label_Nqt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Nqt_2.setObjectName(_fromUtf8("label_Nqt_2"))
        self.gridLayout_5.addWidget(self.label_Nqt_2, 2, 4, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 2)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.gridLayout_5.setColumnStretch(3, 6)
        self.gridLayout_5.setColumnStretch(4, 1)
        self.gridLayout_5.setColumnStretch(5, 4)
        self.lineEdit_recipient = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_recipient.setGeometry(QtCore.QRect(135, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_recipient.setFont(font)
        self.lineEdit_recipient.setObjectName(_fromUtf8("lineEdit_recipient"))
        self.kled_conf1 = KLed(self.groupBox_3)
        self.kled_conf1.setGeometry(QtCore.QRect(365, 25, 91, 91))
        self.kled_conf1.setColor(QtGui.QColor(0, 10, 250))
        self.kled_conf1.setObjectName(_fromUtf8("kled_conf1"))
        self.lineEdit_TXid = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_TXid.setGeometry(QtCore.QRect(135, 70, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_TXid.setFont(font)
        self.lineEdit_TXid.setObjectName(_fromUtf8("lineEdit_TXid"))
        self.label_recipient_2 = QtGui.QLabel(self.groupBox_3)
        self.label_recipient_2.setGeometry(QtCore.QRect(35, 70, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_recipient_2.setFont(font)
        self.label_recipient_2.setObjectName(_fromUtf8("label_recipient_2"))
        self.label_recipient_3 = QtGui.QLabel(self.groupBox_3)
        self.label_recipient_3.setGeometry(QtCore.QRect(20, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_recipient_3.setFont(font)
        self.label_recipient_3.setObjectName(_fromUtf8("label_recipient_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(15, 850, 316, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget_MainDetail.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "nxtPowerTools Main", None))
        self.label_state_numPollsD.setText(_translate("MainWindow", "na", None))
        self.label_state_numberOfAccounts.setText(_translate("MainWindow", "numberOfAccounts", None))
        self.label_state_numVotes.setText(_translate("MainWindow", "numberOfVotes", None))
        self.label_state_numberOfAliasesD.setText(_translate("MainWindow", "na", None))
        self.label_state_numTrades.setText(_translate("MainWindow", "numberOfTrades", None))
        self.label_state_numUnlAccs.setText(_translate("MainWindow", "numUnlockedAccounts", None))
        self.label_state_numTradesD.setText(_translate("MainWindow", "na", None))
        self.label_state_lastBlockchainFeeder.setText(_translate("MainWindow", "lastBlockchainFeeder", None))
        self.label_state_time.setText(_translate("MainWindow", "time", None))
        self.label_state_numberOfAssets.setText(_translate("MainWindow", "numberOfAssets", None))
        self.label_state_totalMemory.setText(_translate("MainWindow", "totalMemory", None))
        self.label_state_numberOfTransactions.setText(_translate("MainWindow", "numberOfTransactions", None))
        self.label_state_numberOfPeersD.setText(_translate("MainWindow", "na", None))
        self.label_state_numberOfPeers.setText(_translate("MainWindow", "numberOfPeers", None))
        self.label_state_lastBlock.setText(_translate("MainWindow", "lastBlock", None))
        self.label_proc.setText(_translate("MainWindow", "availableProcessors", None))
        self.label_state_cumulDiff.setText(_translate("MainWindow", "cumulativeDifficulty", None))
        self.label_state_numberOfOrdersD.setText(_translate("MainWindow", "na", None))
        self.label_state_version.setText(_translate("MainWindow", "version", None))
        self.label_state_numberOfOrders.setText(_translate("MainWindow", "numberOfOrders", None))
        self.label_state_totalEffectiveBalance.setText(_translate("MainWindow", "totalEffectiveBalance", None))
        self.label_state_numberOfBlocks.setText(_translate("MainWindow", "numberOfBlocks", None))
        self.label_state_freeMemory.setText(_translate("MainWindow", "freeMemory", None))
        self.label_state_cumulDiffD.setText(_translate("MainWindow", "na", None))
        self.label_state_lastBlockchainFeederD.setText(_translate("MainWindow", "na", None))
        self.label_state_numberOfAssetsD.setText(_translate("MainWindow", "na", None))
        self.label_state_totalEffectiveBalanceD.setText(_translate("MainWindow", "na", None))
        self.label_state_availableProcessorsD.setText(_translate("MainWindow", "na", None))
        self.label_state_totalMemoryD.setText(_translate("MainWindow", "na", None))
        self.label_state_freeMemoryD.setText(_translate("MainWindow", "na", None))
        self.label_state_maxMemoryD.setText(_translate("MainWindow", "na", None))
        self.label_state_versionD.setText(_translate("MainWindow", "na", None))
        self.label_state_numberOfTransactionsD.setText(_translate("MainWindow", "na", None))
        self.label_state_numberOfBlocksD.setText(_translate("MainWindow", "na", None))
        self.label_state_lastBlockD.setText(_translate("MainWindow", "na", None))
        self.label_state_timeD.setText(_translate("MainWindow", "na", None))
        self.label_state_maxMemory.setText(_translate("MainWindow", "maxMemory", None))
        self.label_state_numUnlAccsD.setText(_translate("MainWindow", "na", None))
        self.label_state_numberOfAccountsD.setText(_translate("MainWindow", "na", None))
        self.label_state_numVotesD.setText(_translate("MainWindow", "na", None))
        self.label_state_numPolls.setText(_translate("MainWindow", "numberOfPolls", None))
        self.label_state_numberOfAliases.setText(_translate("MainWindow", "numberOfAliases", None))
        self.tabWidget_MainDetail.setTabText(self.tabWidget_MainDetail.indexOf(self.tab_state), _translate("MainWindow", "State", None))
        self.label_block_payloadLength.setText(_translate("MainWindow", "payloadLength", None))
        self.label_block_payloadLengthD.setText(_translate("MainWindow", "na", None))
        self.label_block_timeD.setText(_translate("MainWindow", "na", None))
        self.label_block_numberOfTransactions.setText(_translate("MainWindow", "TXs in Block", None))
        self.label_block_transactions.setText(_translate("MainWindow", "transactions", None))
        self.label_block_previousBlockHash.setText(_translate("MainWindow", "prevBlockHash", None))
        self.label_block_nextBlockD.setText(_translate("MainWindow", "na", None))
        self.label_block_prevBlock.setText(_translate("MainWindow", "previousBlock", None))
        self.label_block_addressD.setText(_translate("MainWindow", "na", None))
        self.label_block_baseTargetD.setText(_translate("MainWindow", "na", None))
        self.label_block_previousBlockHashD.setText(_translate("MainWindow", "na", None))
        self.label_block_paylHash.setText(_translate("MainWindow", "payloadHash", None))
        self.label_block_paylHashD.setText(_translate("MainWindow", "na", None))
        self.label_block_height.setText(_translate("MainWindow", "height", None))
        self.label_block_version.setText(_translate("MainWindow", "version", None))
        self.label_block_versionD.setText(_translate("MainWindow", "na", None))
        self.label_block_nextBlock.setText(_translate("MainWindow", "nextBlock", None))
        self.label_block_generationSignatureD.setText(_translate("MainWindow", "na", None))
        self.label_block_totalFeeNQTD.setText(_translate("MainWindow", "na", None))
        self.label_block_heightD.setText(_translate("MainWindow", "na", None))
        self.label_block_generatorD.setText(_translate("MainWindow", "na", None))
        self.label_block_totalFeeNQT.setText(_translate("MainWindow", "totalFeeNQT", None))
        self.label_block_baseTarget.setText(_translate("MainWindow", "baseTarget", None))
        self.label_block_generationSignature.setText(_translate("MainWindow", "gen.Signature", None))
        self.label_block_numberOfTransactionsD.setText(_translate("MainWindow", "na", None))
        self.label_block_generator.setText(_translate("MainWindow", "generator", None))
        self.label_block_prevBlockD.setText(_translate("MainWindow", "na", None))
        self.label_block_address.setText(_translate("MainWindow", "block", None))
        self.label_block_timestamp.setText(_translate("MainWindow", "timestamp", None))
        self.label_block_blockSignature.setText(_translate("MainWindow", "blockSignature", None))
        self.label_block_totAmountNQT.setText(_translate("MainWindow", "totAmountNQT", None))
        self.label_block_totalAmountNQTD.setText(_translate("MainWindow", "na", None))
        self.tabWidget_MainDetail.setTabText(self.tabWidget_MainDetail.indexOf(self.tab_block), _translate("MainWindow", "Block", None))
        self.pb_clearText_2.setText(_translate("MainWindow", "clear", None))
        self.tabWidget_MainDetail.setTabText(self.tabWidget_MainDetail.indexOf(self.tab_TXs), _translate("MainWindow", "TX Monitor", None))
        self.pb_lease.setText(_translate("MainWindow", "lease", None))
        self.label_leaseRec.setText(_translate("MainWindow", "Recipient", None))
        self.label_leasePer.setText(_translate("MainWindow", "Period", None))
        self.label_deadline_2.setText(_translate("MainWindow", "Deadline", None))
        self.label.setText(_translate("MainWindow", "..", None))
        self.gb_ForgeCtrl.setTitle(_translate("MainWindow", "Forge On/Off", None))
        self.label_balanceEff.setText(_translate("MainWindow", "forging\n"
"Power", None))
        self.label_remaining.setText(_translate("MainWindow", "remaining", None))
        self.label_Fdeadline.setText(_translate("MainWindow", "deadline", None))
        self.tabWidget_MainDetail.setTabText(self.tabWidget_MainDetail.indexOf(self.tab_7), _translate("MainWindow", "Accounts", None))
        self.tabWidget_MainDetail.setTabText(self.tabWidget_MainDetail.indexOf(self.tab_4), _translate("MainWindow", "Peers", None))
        self.pb_clearTextEditMSG.setText(_translate("MainWindow", "clear", None))
        self.pb_test1.setText(_translate("MainWindow", "t1", None))
        self.pb_test2.setText(_translate("MainWindow", "t2", None))
        self.pb_test3.setText(_translate("MainWindow", "t3", None))
        self.label_1.setText(_translate("MainWindow", "L1", None))
        self.label_2.setText(_translate("MainWindow", "L2", None))
        self.pb_clearResponse_2.setText(_translate("MainWindow", "clear", None))
        self.tabWidget_MainDetail.setTabText(self.tabWidget_MainDetail.indexOf(self.tab_6), _translate("MainWindow", "Bridge", None))
        self.gb_files.setTitle(_translate("MainWindow", "files", None))
        self.pushButton_nxtWin6.setText(_translate("MainWindow", "Scripts", None))
        self.pushButton_nxtWin7.setText(_translate("MainWindow", "API access", None))
        self.pushButton_TESTBUTTON.setText(_translate("MainWindow", "test", None))
        self.pushButton_nxtWin5.setText(_translate("MainWindow", "nn", None))
        self.pushButton_nxtWin2.setText(_translate("MainWindow", "Asset Exchange", None))
        self.pushButton_nxtWin4.setText(_translate("MainWindow", "Bridge", None))
        self.pushButton_nxtWin1.setText(_translate("MainWindow", "releaseNotes", None))
        self.gb_poll0.setTitle(_translate("MainWindow", "Poll", None))
        self.gb_poll0_2.setTitle(_translate("MainWindow", "Poll", None))
        self.tabWidget_MainDetail.setTabText(self.tabWidget_MainDetail.indexOf(self.tab_8), _translate("MainWindow", "Settings", None))
        self.label_account.setText(_translate("MainWindow", "Account", None))
        self.label_NXTServer.setText(_translate("MainWindow", "Node", None))
        self.label_passPhrase.setText(_translate("MainWindow", "PassPhrase", None))
        self.label_accountName.setText(_translate("MainWindow", "Name", None))
        self.label_pubKey.setText(_translate("MainWindow", "PubKey", None))
        self.label_acctDescr.setText(_translate("MainWindow", "Desc.:", None))
        self.groupBox_Bal_2.setTitle(_translate("MainWindow", "Nxt unconfirmed", None))
        self.label_balanceUnconf_2.setText(_translate("MainWindow", ".", None))
        self.groupBox_Bal.setTitle(_translate("MainWindow", "Nxt", None))
        self.label_balanceUnconf.setText(_translate("MainWindow", ".", None))
        self.pb_sendMoney.setText(_translate("MainWindow", "Send Money", None))
        self.label_amount.setText(_translate("MainWindow", "Amount", None))
        self.label_fee.setText(_translate("MainWindow", "Fee", None))
        self.label_arrow.setText(_translate("MainWindow", "------>", None))
        self.label_deadline.setText(_translate("MainWindow", "Deadline", None))
        self.label_Nxt.setText(_translate("MainWindow", "Nxt", None))
        self.label_Nxt_2.setText(_translate("MainWindow", "Nxt", None))
        self.label_Nqt.setText(_translate("MainWindow", "Nqt", None))
        self.label_Nqt_2.setText(_translate("MainWindow", "Nqt", None))
        self.label_recipient_2.setText(_translate("MainWindow", "TX ID", None))
        self.label_recipient_3.setText(_translate("MainWindow", "Recipient", None))
        self.label_3.setText(_translate("MainWindow", "Donations Welcome: Nxt 8979435596743554427", None))

from PyKDE4.kdeui import KLed
