# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nxtWin2_h900.ui'
#
# Created: Sat Jul  5 16:58:39 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1280, 880)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(10, 10))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 880))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-5, 0, 1280, 880))
        self.tabWidget.setMinimumSize(QtCore.QSize(10, 10))
        self.tabWidget.setMaximumSize(QtCore.QSize(1280, 880))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 310, 716, 526))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.tv_allAssets = QtGui.QTableView(self.groupBox)
        self.tv_allAssets.setGeometry(QtCore.QRect(10, 20, 686, 501))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tv_allAssets.setFont(font)
        self.tv_allAssets.setObjectName(_fromUtf8("tv_allAssets"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(130, 10, 506, 266))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.tv_accAssets = QtGui.QTableView(self.groupBox_2)
        self.tv_accAssets.setGeometry(QtCore.QRect(0, 25, 506, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tv_accAssets.setFont(font)
        self.tv_accAssets.setObjectName(_fromUtf8("tv_accAssets"))
        self.gb_AccSLT = QtGui.QGroupBox(self.tab)
        self.gb_AccSLT.setGeometry(QtCore.QRect(1030, 455, 236, 386))
        self.gb_AccSLT.setCheckable(True)
        self.gb_AccSLT.setObjectName(_fromUtf8("gb_AccSLT"))
        self.lineEdit_acctSlated = QtGui.QLineEdit(self.gb_AccSLT)
        self.lineEdit_acctSlated.setGeometry(QtCore.QRect(15, 40, 210, 22))
        self.lineEdit_acctSlated.setText(_fromUtf8(""))
        self.lineEdit_acctSlated.setObjectName(_fromUtf8("lineEdit_acctSlated"))
        self.groupBox_acctList = QtGui.QGroupBox(self.gb_AccSLT)
        self.groupBox_acctList.setGeometry(QtCore.QRect(10, 140, 226, 236))
        self.groupBox_acctList.setObjectName(_fromUtf8("groupBox_acctList"))
        self.lv_accounts1 = QtGui.QListView(self.groupBox_acctList)
        self.lv_accounts1.setGeometry(QtCore.QRect(5, 30, 210, 200))
        self.lv_accounts1.setObjectName(_fromUtf8("lv_accounts1"))
        self.gb_Nxt_2 = QtGui.QGroupBox(self.gb_AccSLT)
        self.gb_Nxt_2.setGeometry(QtCore.QRect(0, 65, 241, 81))
        self.gb_Nxt_2.setTitle(_fromUtf8(""))
        self.gb_Nxt_2.setObjectName(_fromUtf8("gb_Nxt_2"))
        self.lcdN_acctSLTU_Nqt = QtGui.QLCDNumber(self.gb_Nxt_2)
        self.lcdN_acctSLTU_Nqt.setGeometry(QtCore.QRect(135, 45, 100, 21))
        self.lcdN_acctSLTU_Nqt.setNumDigits(8)
        self.lcdN_acctSLTU_Nqt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdN_acctSLTU_Nqt.setObjectName(_fromUtf8("lcdN_acctSLTU_Nqt"))
        self.lcdN_acctSLTU_Nxt = QtGui.QLCDNumber(self.gb_Nxt_2)
        self.lcdN_acctSLTU_Nxt.setGeometry(QtCore.QRect(0, 40, 120, 26))
        self.lcdN_acctSLTU_Nxt.setNumDigits(9)
        self.lcdN_acctSLTU_Nxt.setDigitCount(9)
        self.lcdN_acctSLTU_Nxt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdN_acctSLTU_Nxt.setObjectName(_fromUtf8("lcdN_acctSLTU_Nxt"))
        self.lcdN_acctSLT_Nqt = QtGui.QLCDNumber(self.gb_Nxt_2)
        self.lcdN_acctSLT_Nqt.setGeometry(QtCore.QRect(135, 15, 100, 21))
        self.lcdN_acctSLT_Nqt.setNumDigits(8)
        self.lcdN_acctSLT_Nqt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdN_acctSLT_Nqt.setObjectName(_fromUtf8("lcdN_acctSLT_Nqt"))
        self.lcdN_acctSLT_Nxt = QtGui.QLCDNumber(self.gb_Nxt_2)
        self.lcdN_acctSLT_Nxt.setGeometry(QtCore.QRect(0, 10, 121, 26))
        self.lcdN_acctSLT_Nxt.setNumDigits(9)
        self.lcdN_acctSLT_Nxt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdN_acctSLT_Nxt.setObjectName(_fromUtf8("lcdN_acctSLT_Nxt"))
        self.label_dot_5 = QtGui.QLabel(self.gb_Nxt_2)
        self.label_dot_5.setGeometry(QtCore.QRect(125, 40, 10, 26))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_dot_5.setFont(font)
        self.label_dot_5.setObjectName(_fromUtf8("label_dot_5"))
        self.label_dot_6 = QtGui.QLabel(self.gb_Nxt_2)
        self.label_dot_6.setGeometry(QtCore.QRect(125, 5, 11, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_dot_6.setFont(font)
        self.label_dot_6.setObjectName(_fromUtf8("label_dot_6"))
        self.groupBox_assetList = QtGui.QGroupBox(self.tab)
        self.groupBox_assetList.setGeometry(QtCore.QRect(1050, 145, 216, 286))
        self.groupBox_assetList.setObjectName(_fromUtf8("groupBox_assetList"))
        self.pb_assToOB = QtGui.QPushButton(self.groupBox_assetList)
        self.pb_assToOB.setGeometry(QtCore.QRect(150, 10, 61, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_assToOB.setFont(font)
        self.pb_assToOB.setObjectName(_fromUtf8("pb_assToOB"))
        self.lineEdit_assetSLT = QtGui.QLineEdit(self.groupBox_assetList)
        self.lineEdit_assetSLT.setGeometry(QtCore.QRect(0, 40, 210, 22))
        self.lineEdit_assetSLT.setObjectName(_fromUtf8("lineEdit_assetSLT"))
        self.lv_assets1 = QtGui.QListView(self.groupBox_assetList)
        self.lv_assets1.setGeometry(QtCore.QRect(0, 70, 210, 200))
        self.lv_assets1.setObjectName(_fromUtf8("lv_assets1"))
        self.gb_AccResid = QtGui.QGroupBox(self.tab)
        self.gb_AccResid.setGeometry(QtCore.QRect(1030, 5, 241, 126))
        self.gb_AccResid.setCheckable(True)
        self.gb_AccResid.setObjectName(_fromUtf8("gb_AccResid"))
        self.lineEdit_acctResid = QtGui.QLineEdit(self.gb_AccResid)
        self.lineEdit_acctResid.setGeometry(QtCore.QRect(25, 30, 210, 22))
        self.lineEdit_acctResid.setObjectName(_fromUtf8("lineEdit_acctResid"))
        self.gb_Nxt = QtGui.QGroupBox(self.gb_AccResid)
        self.gb_Nxt.setGeometry(QtCore.QRect(0, 55, 241, 81))
        self.gb_Nxt.setTitle(_fromUtf8(""))
        self.gb_Nxt.setObjectName(_fromUtf8("gb_Nxt"))
        self.lcdN_acctResU_Nqt = QtGui.QLCDNumber(self.gb_Nxt)
        self.lcdN_acctResU_Nqt.setGeometry(QtCore.QRect(135, 45, 100, 21))
        self.lcdN_acctResU_Nqt.setNumDigits(8)
        self.lcdN_acctResU_Nqt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdN_acctResU_Nqt.setObjectName(_fromUtf8("lcdN_acctResU_Nqt"))
        self.lcdN_acctResU_Nxt = QtGui.QLCDNumber(self.gb_Nxt)
        self.lcdN_acctResU_Nxt.setGeometry(QtCore.QRect(0, 40, 120, 26))
        self.lcdN_acctResU_Nxt.setNumDigits(9)
        self.lcdN_acctResU_Nxt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdN_acctResU_Nxt.setObjectName(_fromUtf8("lcdN_acctResU_Nxt"))
        self.lcdN_acctRes_Nqt = QtGui.QLCDNumber(self.gb_Nxt)
        self.lcdN_acctRes_Nqt.setGeometry(QtCore.QRect(135, 15, 100, 21))
        self.lcdN_acctRes_Nqt.setNumDigits(8)
        self.lcdN_acctRes_Nqt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdN_acctRes_Nqt.setObjectName(_fromUtf8("lcdN_acctRes_Nqt"))
        self.lcdN_acctRes_Nxt = QtGui.QLCDNumber(self.gb_Nxt)
        self.lcdN_acctRes_Nxt.setGeometry(QtCore.QRect(0, 10, 121, 26))
        self.lcdN_acctRes_Nxt.setNumDigits(9)
        self.lcdN_acctRes_Nxt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdN_acctRes_Nxt.setObjectName(_fromUtf8("lcdN_acctRes_Nxt"))
        self.label_dot_2 = QtGui.QLabel(self.gb_Nxt)
        self.label_dot_2.setGeometry(QtCore.QRect(125, 40, 10, 26))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_dot_2.setFont(font)
        self.label_dot_2.setObjectName(_fromUtf8("label_dot_2"))
        self.label_dot = QtGui.QLabel(self.gb_Nxt)
        self.label_dot.setGeometry(QtCore.QRect(125, 5, 11, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_dot.setFont(font)
        self.label_dot.setObjectName(_fromUtf8("label_dot"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(730, 160, 286, 386))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.textEdit_assetDesc = QtGui.QTextEdit(self.groupBox_4)
        self.textEdit_assetDesc.setGeometry(QtCore.QRect(15, 25, 266, 361))
        self.textEdit_assetDesc.setObjectName(_fromUtf8("textEdit_assetDesc"))
        self.pb_getAllAssets = QtGui.QPushButton(self.tab)
        self.pb_getAllAssets.setGeometry(QtCore.QRect(790, 25, 146, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pb_getAllAssets.setFont(font)
        self.pb_getAllAssets.setObjectName(_fromUtf8("pb_getAllAssets"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.textEdit_test = QtGui.QTextEdit(self.tab_2)
        self.textEdit_test.setGeometry(QtCore.QRect(45, 35, 831, 681))
        self.textEdit_test.setObjectName(_fromUtf8("textEdit_test"))
        self.pb_clear = QtGui.QPushButton(self.tab_2)
        self.pb_clear.setGeometry(QtCore.QRect(970, 665, 101, 27))
        self.pb_clear.setObjectName(_fromUtf8("pb_clear"))
        self.pb_1 = QtGui.QPushButton(self.tab_2)
        self.pb_1.setGeometry(QtCore.QRect(970, 460, 101, 27))
        self.pb_1.setObjectName(_fromUtf8("pb_1"))
        self.pb_2 = QtGui.QPushButton(self.tab_2)
        self.pb_2.setGeometry(QtCore.QRect(970, 500, 101, 27))
        self.pb_2.setObjectName(_fromUtf8("pb_2"))
        self.pb_3 = QtGui.QPushButton(self.tab_2)
        self.pb_3.setGeometry(QtCore.QRect(970, 540, 101, 27))
        self.pb_3.setObjectName(_fromUtf8("pb_3"))
        self.pb_4 = QtGui.QPushButton(self.tab_2)
        self.pb_4.setGeometry(QtCore.QRect(970, 580, 101, 27))
        self.pb_4.setObjectName(_fromUtf8("pb_4"))
        self.pb_5 = QtGui.QPushButton(self.tab_2)
        self.pb_5.setGeometry(QtCore.QRect(970, 625, 101, 27))
        self.pb_5.setObjectName(_fromUtf8("pb_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(900, 90, 361, 281))
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setChecked(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox_5)
        self.tableWidget.setGeometry(QtCore.QRect(15, 40, 181, 226))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gb_poll2 = QtGui.QGroupBox(self.groupBox_5)
        self.gb_poll2.setGeometry(QtCore.QRect(275, 5, 81, 41))
        self.gb_poll2.setCheckable(True)
        self.gb_poll2.setObjectName(_fromUtf8("gb_poll2"))
        self.kled_poll2 = KLed(self.gb_poll2)
        self.kled_poll2.setGeometry(QtCore.QRect(0, 20, 26, 21))
        self.kled_poll2.setColor(QtGui.QColor(0, 10, 250))
        self.kled_poll2.setObjectName(_fromUtf8("kled_poll2"))
        self.lineEdit_pollTimer2 = QtGui.QLineEdit(self.gb_poll2)
        self.lineEdit_pollTimer2.setGeometry(QtCore.QRect(25, 20, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_pollTimer2.setFont(font)
        self.lineEdit_pollTimer2.setMaxLength(200)
        self.lineEdit_pollTimer2.setObjectName(_fromUtf8("lineEdit_pollTimer2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionMenu = QtGui.QAction(MainWindow)
        self.actionMenu.setObjectName(_fromUtf8("actionMenu"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "NxtPowerTools - Assets&Accounts", None))
        self.groupBox.setTitle(_translate("MainWindow", "Exchange Assets", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Account Assets", None))
        self.gb_AccSLT.setTitle(_translate("MainWindow", "slated Account", None))
        self.groupBox_acctList.setTitle(_translate("MainWindow", "Account List", None))
        self.label_dot_5.setText(_translate("MainWindow", ".", None))
        self.label_dot_6.setText(_translate("MainWindow", ".", None))
        self.groupBox_assetList.setTitle(_translate("MainWindow", "Asset List", None))
        self.pb_assToOB.setText(_translate("MainWindow", "to OB", None))
        self.gb_AccResid.setTitle(_translate("MainWindow", "resident Account", None))
        self.label_dot_2.setText(_translate("MainWindow", ".", None))
        self.label_dot.setText(_translate("MainWindow", ".", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Asset Description", None))
        self.pb_getAllAssets.setText(_translate("MainWindow", "get Assets", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Assets", None))
        self.pb_clear.setText(_translate("MainWindow", "clear", None))
        self.pb_1.setText(_translate("MainWindow", "1", None))
        self.pb_2.setText(_translate("MainWindow", "2", None))
        self.pb_3.setText(_translate("MainWindow", "3", None))
        self.pb_4.setText(_translate("MainWindow", "4", None))
        self.pb_5.setText(_translate("MainWindow", "5", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Filters", None))
        self.gb_poll2.setTitle(_translate("MainWindow", "Poll", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Filters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Seite", None))
        self.actionMenu.setText(_translate("MainWindow", "nxTrading", None))

from PyKDE4.kdeui import KLed
