# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nxtWin3_h900.ui'
#
# Created: Wed Jul  2 10:58:10 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1280, 846)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(10, 10))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 880))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gb_AssetOrderCtrl = QtGui.QGroupBox(self.centralwidget)
        self.gb_AssetOrderCtrl.setGeometry(QtCore.QRect(0, 35, 366, 816))
        self.gb_AssetOrderCtrl.setCheckable(False)
        self.gb_AssetOrderCtrl.setObjectName(_fromUtf8("gb_AssetOrderCtrl"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.gb_AssetOrderCtrl)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 50, 316, 319))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_asset = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_asset.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_asset.setContentsMargins(2, 5, 2, 8)
        self.gridLayout_asset.setVerticalSpacing(6)
        self.gridLayout_asset.setObjectName(_fromUtf8("gridLayout_asset"))
        self.pb_XferAsset = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pb_XferAsset.setObjectName(_fromUtf8("pb_XferAsset"))
        self.gridLayout_asset.addWidget(self.pb_XferAsset, 7, 0, 1, 1)
        self.pb_AssetID = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pb_AssetID.setObjectName(_fromUtf8("pb_AssetID"))
        self.gridLayout_asset.addWidget(self.pb_AssetID, 0, 0, 1, 1)
        self.lineEdit_recipient = QtGui.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_recipient.setFont(font)
        self.lineEdit_recipient.setMaxLength(2000)
        self.lineEdit_recipient.setObjectName(_fromUtf8("lineEdit_recipient"))
        self.gridLayout_asset.addWidget(self.lineEdit_recipient, 8, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.lineEdit_feeNxt = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_feeNxt.setGeometry(QtCore.QRect(0, 5, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_feeNxt.setFont(font)
        self.lineEdit_feeNxt.setObjectName(_fromUtf8("lineEdit_feeNxt"))
        self.lineEdit_feeNqt = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_feeNqt.setGeometry(QtCore.QRect(100, 5, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_feeNqt.setFont(font)
        self.lineEdit_feeNqt.setObjectName(_fromUtf8("lineEdit_feeNqt"))
        self.label_dot = QtGui.QLabel(self.groupBox_3)
        self.label_dot.setGeometry(QtCore.QRect(90, 5, 11, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_dot.setFont(font)
        self.label_dot.setObjectName(_fromUtf8("label_dot"))
        self.gridLayout_asset.addWidget(self.groupBox_3, 9, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_asset.addWidget(self.label_2, 9, 0, 1, 1)
        self.lineEdit_assetDesc = QtGui.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_assetDesc.setFont(font)
        self.lineEdit_assetDesc.setMaxLength(200)
        self.lineEdit_assetDesc.setObjectName(_fromUtf8("lineEdit_assetDesc"))
        self.gridLayout_asset.addWidget(self.lineEdit_assetDesc, 3, 1, 1, 1)
        self.pb_AssetQTY = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pb_AssetQTY.setObjectName(_fromUtf8("pb_AssetQTY"))
        self.gridLayout_asset.addWidget(self.pb_AssetQTY, 2, 0, 1, 1)
        self.pb_AssetDesc = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pb_AssetDesc.setObjectName(_fromUtf8("pb_AssetDesc"))
        self.gridLayout_asset.addWidget(self.pb_AssetDesc, 3, 0, 1, 1)
        self.pb_issueAsset = QtGui.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pb_issueAsset.setFont(font)
        self.pb_issueAsset.setObjectName(_fromUtf8("pb_issueAsset"))
        self.gridLayout_asset.addWidget(self.pb_issueAsset, 6, 0, 1, 1)
        self.pb_AssetIssuer = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pb_AssetIssuer.setObjectName(_fromUtf8("pb_AssetIssuer"))
        self.gridLayout_asset.addWidget(self.pb_AssetIssuer, 5, 0, 1, 1)
        self.lineEdit_assetID = QtGui.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_assetID.setFont(font)
        self.lineEdit_assetID.setMaxLength(200)
        self.lineEdit_assetID.setObjectName(_fromUtf8("lineEdit_assetID"))
        self.gridLayout_asset.addWidget(self.lineEdit_assetID, 0, 1, 1, 1)
        self.label_recipient = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_recipient.setAlignment(QtCore.Qt.AlignCenter)
        self.label_recipient.setObjectName(_fromUtf8("label_recipient"))
        self.gridLayout_asset.addWidget(self.label_recipient, 8, 0, 1, 1)
        self.lineEdit_assetIssuer = QtGui.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_assetIssuer.setFont(font)
        self.lineEdit_assetIssuer.setMaxLength(200)
        self.lineEdit_assetIssuer.setObjectName(_fromUtf8("lineEdit_assetIssuer"))
        self.gridLayout_asset.addWidget(self.lineEdit_assetIssuer, 5, 1, 1, 1)
        self.lineEdit_assetQTY = QtGui.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_assetQTY.setFont(font)
        self.lineEdit_assetQTY.setMaxLength(200)
        self.lineEdit_assetQTY.setObjectName(_fromUtf8("lineEdit_assetQTY"))
        self.gridLayout_asset.addWidget(self.lineEdit_assetQTY, 2, 1, 1, 1)
        self.pb_AssetName = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pb_AssetName.setObjectName(_fromUtf8("pb_AssetName"))
        self.gridLayout_asset.addWidget(self.pb_AssetName, 1, 0, 1, 1)
        self.lineEdit_assetName = QtGui.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_assetName.setFont(font)
        self.lineEdit_assetName.setMaxLength(200)
        self.lineEdit_assetName.setObjectName(_fromUtf8("lineEdit_assetName"))
        self.gridLayout_asset.addWidget(self.lineEdit_assetName, 1, 1, 1, 1)
        self.gb_issue = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.gb_issue.setTitle(_fromUtf8(""))
        self.gb_issue.setObjectName(_fromUtf8("gb_issue"))
        self.cb_issueAsset = QtGui.QCheckBox(self.gb_issue)
        self.cb_issueAsset.setGeometry(QtCore.QRect(5, 0, 66, 26))
        self.cb_issueAsset.setObjectName(_fromUtf8("cb_issueAsset"))
        self.lineEdit_dec = QtGui.QLineEdit(self.gb_issue)
        self.lineEdit_dec.setGeometry(QtCore.QRect(170, 5, 31, 21))
        self.lineEdit_dec.setObjectName(_fromUtf8("lineEdit_dec"))
        self.label = QtGui.QLabel(self.gb_issue)
        self.label.setGeometry(QtCore.QRect(105, 5, 66, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_asset.addWidget(self.gb_issue, 6, 1, 1, 1)
        self.gb_Xfer = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.gb_Xfer.setTitle(_fromUtf8(""))
        self.gb_Xfer.setObjectName(_fromUtf8("gb_Xfer"))
        self.cb_Xfer = QtGui.QCheckBox(self.gb_Xfer)
        self.cb_Xfer.setGeometry(QtCore.QRect(5, 0, 86, 26))
        self.cb_Xfer.setObjectName(_fromUtf8("cb_Xfer"))
        self.lineEdit_XferComment = QtGui.QLineEdit(self.gb_Xfer)
        self.lineEdit_XferComment.setGeometry(QtCore.QRect(135, 5, 71, 16))
        self.lineEdit_XferComment.setObjectName(_fromUtf8("lineEdit_XferComment"))
        self.label_comment = QtGui.QLabel(self.gb_Xfer)
        self.label_comment.setGeometry(QtCore.QRect(100, 5, 36, 16))
        self.label_comment.setObjectName(_fromUtf8("label_comment"))
        self.gridLayout_asset.addWidget(self.gb_Xfer, 7, 1, 1, 1)
        self.gridLayoutWidget_7 = QtGui.QWidget(self.gb_AssetOrderCtrl)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(15, 570, 331, 224))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_orders = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_orders.setMargin(0)
        self.gridLayout_orders.setObjectName(_fromUtf8("gridLayout_orders"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_orders.addItem(spacerItem, 5, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_orders.addItem(spacerItem1, 3, 0, 1, 1)
        self.label_Price = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_Price.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Price.setObjectName(_fromUtf8("label_Price"))
        self.gridLayout_orders.addWidget(self.label_Price, 4, 0, 1, 1)
        self.cb_bidOrder = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.cb_bidOrder.setObjectName(_fromUtf8("cb_bidOrder"))
        self.gridLayout_orders.addWidget(self.cb_bidOrder, 9, 1, 1, 1)
        self.label_expire = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_expire.setAlignment(QtCore.Qt.AlignCenter)
        self.label_expire.setObjectName(_fromUtf8("label_expire"))
        self.gridLayout_orders.addWidget(self.label_expire, 7, 0, 1, 1)
        self.pb_placeAsk = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.pb_placeAsk.setObjectName(_fromUtf8("pb_placeAsk"))
        self.gridLayout_orders.addWidget(self.pb_placeAsk, 10, 0, 1, 1)
        self.label_Vol = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_Vol.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Vol.setObjectName(_fromUtf8("label_Vol"))
        self.gridLayout_orders.addWidget(self.label_Vol, 5, 0, 1, 1)
        self.pb_cancelOrder = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.pb_cancelOrder.setObjectName(_fromUtf8("pb_cancelOrder"))
        self.gridLayout_orders.addWidget(self.pb_cancelOrder, 8, 0, 1, 1)
        self.cb_askOrder = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.cb_askOrder.setObjectName(_fromUtf8("cb_askOrder"))
        self.gridLayout_orders.addWidget(self.cb_askOrder, 10, 1, 1, 1)
        self.pb_placeBid = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.pb_placeBid.setObjectName(_fromUtf8("pb_placeBid"))
        self.gridLayout_orders.addWidget(self.pb_placeBid, 9, 0, 1, 1)
        self.lineEdit_Vol2 = QtGui.QLineEdit(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Vol2.setFont(font)
        self.lineEdit_Vol2.setMaxLength(200)
        self.lineEdit_Vol2.setObjectName(_fromUtf8("lineEdit_Vol2"))
        self.gridLayout_orders.addWidget(self.lineEdit_Vol2, 5, 3, 1, 1)
        self.pb_matchOrder = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.pb_matchOrder.setObjectName(_fromUtf8("pb_matchOrder"))
        self.gridLayout_orders.addWidget(self.pb_matchOrder, 3, 3, 1, 1)
        self.cb_cancelOrder = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.cb_cancelOrder.setObjectName(_fromUtf8("cb_cancelOrder"))
        self.gridLayout_orders.addWidget(self.cb_cancelOrder, 8, 1, 1, 1)
        self.lineEdit_expire = QtGui.QLineEdit(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_expire.setFont(font)
        self.lineEdit_expire.setMaxLength(300)
        self.lineEdit_expire.setObjectName(_fromUtf8("lineEdit_expire"))
        self.gridLayout_orders.addWidget(self.lineEdit_expire, 7, 1, 1, 1)
        self.lineEdit_Vol = QtGui.QLineEdit(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Vol.setFont(font)
        self.lineEdit_Vol.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_Vol.setMaxLength(200)
        self.lineEdit_Vol.setEchoMode(QtGui.QLineEdit.Normal)
        self.lineEdit_Vol.setObjectName(_fromUtf8("lineEdit_Vol"))
        self.gridLayout_orders.addWidget(self.lineEdit_Vol, 5, 1, 1, 1)
        self.lineEdit_price = QtGui.QLineEdit(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_price.setFont(font)
        self.lineEdit_price.setMaxLength(200)
        self.lineEdit_price.setObjectName(_fromUtf8("lineEdit_price"))
        self.gridLayout_orders.addWidget(self.lineEdit_price, 4, 1, 1, 1)
        self.label_composeOrder = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_composeOrder.setObjectName(_fromUtf8("label_composeOrder"))
        self.gridLayout_orders.addWidget(self.label_composeOrder, 3, 1, 1, 1)
        self.lineEdit_price2 = QtGui.QLineEdit(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_price2.setFont(font)
        self.lineEdit_price2.setMaxLength(200)
        self.lineEdit_price2.setObjectName(_fromUtf8("lineEdit_price2"))
        self.gridLayout_orders.addWidget(self.lineEdit_price2, 4, 3, 1, 1)
        self.lineEdit_expire2 = QtGui.QLineEdit(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_expire2.setFont(font)
        self.lineEdit_expire2.setMaxLength(300)
        self.lineEdit_expire2.setObjectName(_fromUtf8("lineEdit_expire2"))
        self.gridLayout_orders.addWidget(self.lineEdit_expire2, 7, 3, 1, 1)
        self.cb_bidOrder2 = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.cb_bidOrder2.setObjectName(_fromUtf8("cb_bidOrder2"))
        self.gridLayout_orders.addWidget(self.cb_bidOrder2, 9, 3, 1, 1)
        self.cb_askOrder2 = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.cb_askOrder2.setObjectName(_fromUtf8("cb_askOrder2"))
        self.gridLayout_orders.addWidget(self.cb_askOrder2, 10, 3, 1, 1)
        self.groupBox_orderSlate = QtGui.QGroupBox(self.gb_AssetOrderCtrl)
        self.groupBox_orderSlate.setGeometry(QtCore.QRect(10, 470, 336, 61))
        self.groupBox_orderSlate.setTitle(_fromUtf8(""))
        self.groupBox_orderSlate.setObjectName(_fromUtf8("groupBox_orderSlate"))
        self.cb_oIss = QtGui.QCheckBox(self.groupBox_orderSlate)
        self.cb_oIss.setGeometry(QtCore.QRect(270, 10, 61, 22))
        self.cb_oIss.setObjectName(_fromUtf8("cb_oIss"))
        self.lineEdit_orderIss = QtGui.QLineEdit(self.groupBox_orderSlate)
        self.lineEdit_orderIss.setGeometry(QtCore.QRect(85, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_orderIss.setFont(font)
        self.lineEdit_orderIss.setMaxLength(200)
        self.lineEdit_orderIss.setObjectName(_fromUtf8("lineEdit_orderIss"))
        self.label_OrderId = QtGui.QLabel(self.groupBox_orderSlate)
        self.label_OrderId.setGeometry(QtCore.QRect(0, 40, 70, 17))
        self.label_OrderId.setObjectName(_fromUtf8("label_OrderId"))
        self.lineEdit_orderId = QtGui.QLineEdit(self.groupBox_orderSlate)
        self.lineEdit_orderId.setGeometry(QtCore.QRect(85, 35, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_orderId.setFont(font)
        self.lineEdit_orderId.setMaxLength(200)
        self.lineEdit_orderId.setObjectName(_fromUtf8("lineEdit_orderId"))
        self.label_OrderIssuer = QtGui.QLabel(self.groupBox_orderSlate)
        self.label_OrderIssuer.setGeometry(QtCore.QRect(0, 15, 81, 17))
        self.label_OrderIssuer.setObjectName(_fromUtf8("label_OrderIssuer"))
        self.kled_conf3 = KLed(self.gb_AssetOrderCtrl)
        self.kled_conf3.setGeometry(QtCore.QRect(20, 395, 51, 51))
        self.kled_conf3.setColor(QtGui.QColor(0, 10, 250))
        self.kled_conf3.setObjectName(_fromUtf8("kled_conf3"))
        self.lineEdit_serverReply1 = QtGui.QLineEdit(self.gb_AssetOrderCtrl)
        self.lineEdit_serverReply1.setGeometry(QtCore.QRect(95, 400, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_serverReply1.setFont(font)
        self.lineEdit_serverReply1.setMaxLength(200)
        self.lineEdit_serverReply1.setObjectName(_fromUtf8("lineEdit_serverReply1"))
        self.lineEdit_serverReply2 = QtGui.QLineEdit(self.gb_AssetOrderCtrl)
        self.lineEdit_serverReply2.setGeometry(QtCore.QRect(95, 425, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_serverReply2.setFont(font)
        self.lineEdit_serverReply2.setMaxLength(200)
        self.lineEdit_serverReply2.setObjectName(_fromUtf8("lineEdit_serverReply2"))
        self.gb_poll3 = QtGui.QGroupBox(self.gb_AssetOrderCtrl)
        self.gb_poll3.setGeometry(QtCore.QRect(225, 0, 136, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gb_poll3.setFont(font)
        self.gb_poll3.setCheckable(True)
        self.gb_poll3.setObjectName(_fromUtf8("gb_poll3"))
        self.lineEdit_pollTimer3 = QtGui.QLineEdit(self.gb_poll3)
        self.lineEdit_pollTimer3.setGeometry(QtCore.QRect(50, 3, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_pollTimer3.setFont(font)
        self.lineEdit_pollTimer3.setMaxLength(200)
        self.lineEdit_pollTimer3.setObjectName(_fromUtf8("lineEdit_pollTimer3"))
        self.kled_poll3 = KLed(self.gb_poll3)
        self.kled_poll3.setGeometry(QtCore.QRect(105, 0, 26, 21))
        self.kled_poll3.setColor(QtGui.QColor(0, 10, 250))
        self.kled_poll3.setObjectName(_fromUtf8("kled_poll3"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(375, 0, 486, 870))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.tv_allAssAskOrders = QtGui.QTableView(self.groupBox_6)
        self.tv_allAssAskOrders.setGeometry(QtCore.QRect(5, 30, 470, 400))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tv_allAssAskOrders.setFont(font)
        self.tv_allAssAskOrders.setObjectName(_fromUtf8("tv_allAssAskOrders"))
        self.tv_allAssBidOrders = QtGui.QTableView(self.groupBox_6)
        self.tv_allAssBidOrders.setGeometry(QtCore.QRect(5, 440, 470, 400))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tv_allAssBidOrders.setFont(font)
        self.tv_allAssBidOrders.setObjectName(_fromUtf8("tv_allAssBidOrders"))
        self.gb_tradeFilters = QtGui.QGroupBox(self.centralwidget)
        self.gb_tradeFilters.setGeometry(QtCore.QRect(885, 0, 386, 856))
        self.gb_tradeFilters.setFlat(True)
        self.gb_tradeFilters.setCheckable(False)
        self.gb_tradeFilters.setObjectName(_fromUtf8("gb_tradeFilters"))
        self.label_3 = QtGui.QLabel(self.gb_tradeFilters)
        self.label_3.setGeometry(QtCore.QRect(250, 10, 66, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_numTrd = QtGui.QLineEdit(self.gb_tradeFilters)
        self.lineEdit_numTrd.setGeometry(QtCore.QRect(315, 10, 66, 21))
        self.lineEdit_numTrd.setObjectName(_fromUtf8("lineEdit_numTrd"))
        self.tv_trades1 = QtGui.QTableView(self.gb_tradeFilters)
        self.tv_trades1.setGeometry(QtCore.QRect(10, 85, 360, 721))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tv_trades1.setFont(font)
        self.tv_trades1.setObjectName(_fromUtf8("tv_trades1"))
        self.gb_timeInterval = QtGui.QGroupBox(self.gb_tradeFilters)
        self.gb_timeInterval.setGeometry(QtCore.QRect(50, 35, 196, 51))
        self.gb_timeInterval.setCheckable(True)
        self.gb_timeInterval.setObjectName(_fromUtf8("gb_timeInterval"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.gb_timeInterval)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 160, 21))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(25)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit_tradesStart = QtGui.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_tradesStart.setFont(font)
        self.lineEdit_tradesStart.setObjectName(_fromUtf8("lineEdit_tradesStart"))
        self.gridLayout_2.addWidget(self.lineEdit_tradesStart, 0, 0, 1, 1)
        self.lineEdit_tradesStop = QtGui.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_tradesStop.setFont(font)
        self.lineEdit_tradesStop.setObjectName(_fromUtf8("lineEdit_tradesStop"))
        self.gridLayout_2.addWidget(self.lineEdit_tradesStop, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionMenu = QtGui.QAction(MainWindow)
        self.actionMenu.setObjectName(_fromUtf8("actionMenu"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "NxtPowerTools Order Book", None))
        self.gb_AssetOrderCtrl.setTitle(_translate("MainWindow", "Asset and Order Control", None))
        self.pb_XferAsset.setText(_translate("MainWindow", "X-fer", None))
        self.pb_AssetID.setText(_translate("MainWindow", "AssetID", None))
        self.label_dot.setText(_translate("MainWindow", ".", None))
        self.label_2.setText(_translate("MainWindow", "Fee [Nxt.Nqt]", None))
        self.pb_AssetQTY.setText(_translate("MainWindow", "AssetQTY", None))
        self.pb_AssetDesc.setText(_translate("MainWindow", "AssetDesc", None))
        self.pb_issueAsset.setText(_translate("MainWindow", "issueAsset", None))
        self.pb_AssetIssuer.setText(_translate("MainWindow", "AssetIssuer", None))
        self.label_recipient.setText(_translate("MainWindow", "Recipient", None))
        self.pb_AssetName.setText(_translate("MainWindow", "AssetName", None))
        self.cb_issueAsset.setText(_translate("MainWindow", "issue", None))
        self.label.setText(_translate("MainWindow", "Decimals", None))
        self.cb_Xfer.setText(_translate("MainWindow", "transfer", None))
        self.label_comment.setText(_translate("MainWindow", "cmt.", None))
        self.label_Price.setText(_translate("MainWindow", "Price [Nqt]", None))
        self.cb_bidOrder.setText(_translate("MainWindow", "BUY", None))
        self.label_expire.setText(_translate("MainWindow", "expire", None))
        self.pb_placeAsk.setText(_translate("MainWindow", "SELL", None))
        self.label_Vol.setText(_translate("MainWindow", "Vol", None))
        self.pb_cancelOrder.setText(_translate("MainWindow", "cancel", None))
        self.cb_askOrder.setText(_translate("MainWindow", "SELL", None))
        self.pb_placeBid.setText(_translate("MainWindow", "BUY", None))
        self.pb_matchOrder.setText(_translate("MainWindow", "MATCH", None))
        self.cb_cancelOrder.setText(_translate("MainWindow", "cancel", None))
        self.label_composeOrder.setText(_translate("MainWindow", "compose", None))
        self.cb_bidOrder2.setText(_translate("MainWindow", "BUY", None))
        self.cb_askOrder2.setText(_translate("MainWindow", "SELL", None))
        self.cb_oIss.setText(_translate("MainWindow", "slate", None))
        self.label_OrderId.setText(_translate("MainWindow", "OrderId", None))
        self.label_OrderIssuer.setText(_translate("MainWindow", "OrderIssuer", None))
        self.gb_poll3.setTitle(_translate("MainWindow", "Poll", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Orderbook1", None))
        self.gb_tradeFilters.setTitle(_translate("MainWindow", "Trades", None))
        self.label_3.setText(_translate("MainWindow", "numTrds", None))
        self.gb_timeInterval.setTitle(_translate("MainWindow", "time interval", None))
        self.actionMenu.setText(_translate("MainWindow", "nxTrading", None))

from PyKDE4.kdeui import KLed
